### ISSUE TITLE
Storage_secret missing with ui.run_with and on_connect 

### ISSUE THREAD

**Issue by kleynjan** [zauberzeug/nicegui#3209] opened 2024-06-12 10:12 UTC
### Description

I get RuntimeError('app.storage.user needs a storage_secret passed in ui.run()') when trying to access app.storage.user in an on_connect event handler from a FastAPI run_with app. In the page function, app.storage.user works as normal. Possibly related to #2578 . Running 1.4.26.

Use case: check browser capabilities upon connection and store them in session state. 

There is a connected browser at this point (in the on_connect), so I'd expect to be able to access the session. I can live with it if this scenario is not supported using on_connect (I will go back to 'await ui.context.client.connected' in the page functions), but in that case it'd be nice to see the limitation documented or explained. 

My runtime env is uvicorn -> fastapi app -> nicegui app, so I need to use ui.run_with. 

Minimal example:  
```python
# test_connect.py

from fastapi import FastAPI
from nicegui import ui, app

fastapi_app = FastAPI()

def on_connect():
    app.storage.user["connected"] = True

@ui.page("/")
def index():
    ui.label("Index page")
    app.storage.user["connected"] = False
    app.storage.user["some_var"] = "OK"

app.on_connect(on_connect)
ui.run_with(fastapi_app, storage_secret="abrakadabra")

## this is run with: uvicorn test_connect:fastapi_app

**Comment by kleynjan** [comment] 2024-06-12 18:32
Maybe the relevant doc is: "The user storage and browser storage are only available within page builder functions". 

In that case, the storage_secret error message may have put me on the wrong track. Feel free to close.

**Comment by falkoschindler** [comment] 2024-06-16 14:03
Thanks for reporting this problem, @kleynjan!
It looks like it is a duplicate of #2520.

**Closed by falkoschindler** 2024-06-16 14:03 UTC
