### ISSUE TITLE
What is wrong with on_value_change?

### ISSUE THREAD

**Issue by ed2050** [zauberzeug/nicegui#3259] opened 2024-06-21 17:35 UTC
### Description

Apparently `radio.on_value_change` does nothing.  Tried many permutations, can't ever get it to call the callback handler.

Run this code.  Change the radio selection and see what happens.  For me it's nothing.  No notifications, no console (terminal) messages.  TF is going on??

```py
import nicegui
from nicegui import ui

def report (*args, **kwargs) :
    msg = f'got value change : { args } ; { kwargs }'
    print (msg)
    ui.notify (msg)

def mainpage () :
    ui.label ('test page')
    myradio = ui.radio ([ 1,2,3 ])
    myradio.on_value_change (report)

if __name__ in {"__main__", "__mp_main__"} :
    ui.run (dark = True)
    mainpage ()
```

**Comment by falkoschindler** [comment] 2024-06-21 18:01
Hi @ed2050,

I can't reproduce the behavior you're describing. When I run your code _or_ this simplified version
```py
ui.radio([1, 2, 3]).on_value_change(lambda *args, **kwargs: print(f'{args=}, {kwargs=}'))
```
I do see messages in the terminal.

**Comment by falkoschindler** [comment] 2024-06-21 18:19
Sure, that's possible. Version 1.3.16 is almost 9 months old and I don't remember everything we changed/fixed since then. Since the problem doesn't exist with the latest 1.4.27, I'll close this issue.

**Closed by falkoschindler** 2024-06-21 18:19 UTC

**Comment by ed2050** [comment] 2024-06-21 18:35
9 months, god forbid.  Let's all reinstall our entire web stack from the ground up every week.  How could anyone still support software from the dark ages of 9 months ago?  We were just banging rocks back then.  

I'm fine with you closing it.  You tested and confirmed it's not a universal problem.  Thank you for that.

It's premature to rule out other possible causes (such as: intermittent bug, trigger condition not in your environment, etc).  And many developers are turned off by chasing their tails with constant upgrades.  I'll look into it more if I have time.
