### ISSUE TITLE
The pyinstaller didn't work in nicegui 1.3.7

### ISSUE THREAD

**Issue by v479038280** [zauberzeug/nicegui#1328] opened 2023-08-03 15:16 UTC
### Description

Here is the output
```
Traceback (most recent call last):
  File "F:\Folder_Share\nicegui\project\build.py", line 13, in <module>  
    '--add-data', f'{Path(nicegui.__file__).parent}{os.pathsep}nicegui', 
  File "D:\Program Files\python\lib\pathlib.py", line 1082, in __new__   
    self = cls._from_parts(args, init=False)
  File "D:\Program Files\python\lib\pathlib.py", line 707, in _from_parts
    drv, root, parts = self._parse_args(args)
  File "D:\Program Files\python\lib\pathlib.py", line 691, in _parse_args
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType 
```

**Comment by falkoschindler** [comment] 2023-08-03 17:56
@v479038280 Please give some more information:
- Does the problem occur with a very simple Hello World example?
- What does the build script look like?
- Does the very same code work with NiceGUI 1.3.6?
- Which OS and Python version are you working with?

**Comment by v479038280** [comment] 2023-08-04 02:46
Here is the output of a simple Hello world ( ```
 from nicegui import ui

ui.label('hello world')

ui.run()
```)


```
The 'typing' package is an obsolete backport of a standard library package and is incompatible with PyInstaller. Please remove this package (located in D:\Program Files\python\Lib\site-packages) using
    "D:\Program Files\python\python.exe" -m pip uninstall typing
then try again.
```

And the build script 
```
cmd = [
    'python',
    '-m', 'PyInstaller',
    'hello_world.py', # your main file with ui.run()
    '--name', 'app002', # name of your app
    '--onefile',
    # '--windowed', # prevent console appearing, only use with ui.run(native=True, ...)
    '--add-data', f'{Path(nicegui.__file__).parent}{os.pathsep}nicegui',
    '-i',  './favicon.ico',
]
```
There is no such problem with NiceGui1.3.6,thouth   the ' '--windowed','didn't work .

I'm using Windows10  64 ,and python 3.11.4

**Comment by falkoschindler** [comment] 2023-08-04 05:31
I'm not sure about the implications of the warning (or error?) about the typing package. You might want to follow the instruction and uninstall it.

Apart from that, can you debug the expression `f'{Path(nicegui.__file__).parent}{os.pathsep}nicegui'`? It looks like `nicegui.__file__` is `None`. Can you confirm that?

**Comment by v479038280** [comment] 2023-08-06 08:12
I test the hello world with  nuitka ,one time pass . The exe file is 289Kb ,  https://github.com/v479038280/streamlit_rep/blob/master/hello_world.exe。and It works fine,

**Comment by falkoschindler** [comment] 2023-08-06 10:33
As far as I understand, your build.py raises the error "TypeError: expected str, bytes or os.PathLike object, not NoneType" because of the expression `f'{Path(nicegui.__file__).parent}{os.pathsep}nicegui'`.
So you should debug it within the **build.py** script.

**Comment by v479038280** [comment] 2023-08-06 12:10
> As far as I understand, your build.py raises the error "TypeError: expected str, bytes or os.PathLike object, not NoneType" because of the expression `f'{Path(nicegui.__file__).parent}{os.pathsep}nicegui'`. So you should debug it within the **build.py** script.

That's the problem .I missed a ',' in the last line

**Comment by falkoschindler** [comment] 2023-08-06 15:45
Where did you miss a comma?
The code you showed in https://github.com/zauberzeug/nicegui/issues/1328#issuecomment-1664896768 seems to be correct in this respect.

Anyway, is the problem solved?

**Comment by v479038280** [comment] 2023-08-06 16:06
There is still other problem ,the exe couldn't run succesesfully. 
I found nuitka is better than pyinstaller, I'm trying to use nuitka

**Comment by falkoschindler** [comment] 2023-08-06 17:20
@v479038280 If there's an issue with NiceGUI and PyInstaller, we'd really like to help and find the root cause. But it would really help a lot if you could
1. answer our questions as precisely as possible and
2. give more information about the problems you're facing.

So gain: Can we close this issue?

If not: What do you mean with "couldn't run succesesfully"? What happens? Are there error messages? How did the code change with respect to your previous post?

**Comment by v479038280** [comment] 2023-08-06 17:26
I closed it











                       
Original Email
                       
                     

Sender:"Falko Schindler"< ***@***.*** &gt;;

Sent Time:2023/8/7 1:20

To:"zauberzeug/nicegui"< ***@***.*** &gt;;

Cc recipient:"v479038280"< ***@***.*** &gt;;"Mention"< ***@***.*** &gt;;

Subject:Re: [zauberzeug/nicegui] The pyinstaller didn&#39;t work in nicegui 1.3.7(Issue #1328)




 
@v479038280 If there's an issue with NiceGUI and PyInstaller, we'd really like to help and find the root cause. But it would really help a lot if you could
  
answer our questions as precisely as possible and
 
give more information about the problems you're facing.
  
So gain: Can we close this issue?
 
If not: What do you mean with "couldn't run succesesfully"? What happens? Are there error messages? How did the code change with respect to your previous post?

**Comment by PTruscott** [comment] 2023-09-07 20:35
I think this ticket should be reopened.  With the standard "hello world" script 
`from nicegui import ui
ui.label('hello world')
ui.run()`

After being built with `pyinstaller -F .\main.py` and trying to run it crashes and gives

`Traceback (most recent call last):
  File "main.py", line 3, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 385, in exec_module
  File "nicegui\__init__.py", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 385, in exec_module
  File "nicegui\ui.py", line 166, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 385, in exec_module
  File "nicegui\elements\upload.py", line 7, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 385, in exec_module
  File "nicegui\nicegui.py", line 31, in <module>
  File "starlette\staticfiles.py", line 57, in __init__
RuntimeError: Directory 'C:\Users\darth\AppData\Local\Temp\_MEI69842\nicegui\static' does not exist
[27628] Failed to execute script 'main' due to unhandled exception!`

Would love this to be fixed, let me know if I can help in any way

**Comment by rodja** [comment] 2023-09-08 03:02
@PTruscott Have you seen https://nicegui.io/documentation#package_for_installation? A plain `pyinstaller -F .\main.py` is not enough. You'll need the parameters from the provided `build.py`.

**Comment by PTruscott** [comment] 2023-09-08 09:13
Apologies, will confess I was an idiot here!  Glad this works using the build script.  

Interesting note is when developing in Pycharm on Windows, due to pycharms package management and venv the suggested didn't work, but I just turned it to: 
```
import os
import subprocess
from pathlib import Path
import nicegui

cmd = [
    'pyinstaller',
    'main.py', # your main file with ui.run()
    '--name', 'myapp', # name of your app
    '--onefile',
    #'--windowed', # prevent console appearing, only use with ui.run(native=True, ...)
    '--add-data', f'{Path(nicegui.__file__).parent}{os.pathsep}nicegui'
]
subprocess.call(cmd)
```

Which then builds and loads fine

**Closed** 2023-09-08 09:26 UTC
Labels: question
