### ISSUE TITLE
Bus error crash on aarch64 - Caused by orjson

### ISSUE THREAD

**Issue by mattie47** [zauberzeug/nicegui#3200] opened 2024-06-11 01:49 UTC
### Description

Hi,

I wanted to document an issue with an external library I found after upgrading nicegui.

The issue I found is that when we ran our application, it would crash as soon as the first web request is received, with the last terminal output being "Bus error".

We tried to exclude our application from the mix for testing, and found the example in readme.md works fine, so I guess orjson isn't needed for that. 

After going down quite a rabbit hole (we use canbus and i2c in our application, so first thought "Bus error" was coming from somewhere else), we came across this stackoverflow post:
https://stackoverflow.com/questions/61324136/how-to-solve-bus-error-core-dumped-in-python

Where when we ran the gdb commands:

```

Thread 12 "python3" received signal SIGBUS, Bus error.
[Switching to Thread 0xed1ff440 (LWP 13991)]
0xf68668bc in <orjson::serialize::per_type::unicode::StrSerializer as serde::ser::Serialize>::serialize ()
   from /home/pi/.local/lib/python3.9/site-packages/orjson/orjson.cpython-39-arm-linux-gnueabihf.so
(gdb) backtrace
#0  0xf68668bc in <orjson::serialize::per_type::unicode::StrSerializer as serde::ser::Serialize>::serialize ()
   from /home/pi/.local/lib/python3.9/site-packages/orjson/orjson.cpython-39-arm-linux-gnueabihf.so
#1  0xf68648e0 in <orjson::serialize::per_type::dict::DictNonStrKey as serde::ser::Serialize>::serialize ()
   from /home/pi/.local/lib/python3.9/site-packages/orjson/orjson.cpython-39-arm-linux-gnueabihf.so
#2  0xf68673b0 in <orjson::serialize::serializer::PyObjectSerializer as serde::ser::Serialize>::serialize ()
   from /home/pi/.local/lib/python3.9/site-packages/orjson/orjson.cpython-39-arm-linux-gnueabihf.so
#3  0xf68648e0 in <orjson::serialize::per_type::dict::DictNonStrKey as serde::ser::Serialize>::serialize ()
   from /home/pi/.local/lib/python3.9/site-packages/orjson/orjson.cpython-39-arm-linux-gnueabihf.so
#4  0xf68673b0 in <orjson::serialize::serializer::PyObjectSerializer as serde::ser::Serialize>::serialize ()
   from /home/pi/.local/lib/python3.9/site-packages/orjson/orjson.cpython-39-arm-linux-gnueabihf.so
#5  0xf68648e0 in <orjson::serialize::per_type::dict::DictNonStrKey as serde::ser::Serialize>::serialize ()
   from /home/pi/.local/lib/python3.9/site-packages/orjson/orjson.cpython-39-arm-linux-gnueabihf.so
#6  0xf68673b0 in <orjson::serialize::serializer::PyObjectSerializer as serde::ser::Serialize>::serialize ()
   from /home/pi/.local/lib/python3.9/site-packages/orjson/orjson.cpython-39-arm-linux-gnueabihf.so
#7  0xf68648e0 in <orjson::serialize::per_type::dict::DictNonStrKey as serde::ser::Serialize>::serialize ()
   from /home/pi/.local/lib/python3.9/site-packages/orjson/orjson.cpython-39-arm-linux-gnueabihf.so
#8  0xf68673b0 in <orjson::serialize::serializer::PyObjectSerializer as serde::ser::Serialize>::serialize ()
   from /home/pi/.local/lib/python3.9/site-packages/orjson/orjson.cpython-39-arm-linux-gnueabihf.so
#9  0xf6868dd8 in dumps () from /home/pi/.local/lib/python3.9/site-packages/orjson/orjson.cpython-39-arm-linux-gnueabihf.so
#10 0x000a8404 in ?? ()
Backtrace stopped: previous frame identical to this frame (corrupt stack?)
(gdb) exit
```

Which pointed us to orjson.

I can now see https://github.com/ijl/orjson/issues/495 exists, with the similar issue found with hass - https://github.com/home-assistant/core/issues/118507

**So - our workaround? Downgrade orjson to 3.10.1**

```
pip3 install --upgrade orjson==3.10.1
```

Nicegui is now working fine for us again, but we will keep an eye on updates to orjson.

Thanks,

Matt

**Comment by falkoschindler** [comment] 2024-06-16 06:52
Thanks for reporting this issue, @mattie47!

Which version of orjson is the faulty one? Have you already tried the most recent 3.10.4 or 3.10.5 which have been released this week?
Do you think you can reproduce the problem without NiceGUI, i.e. simply (de-)serializing a string with orjson?

**Comment by falkoschindler** [comment] 2024-06-28 06:00
I'll close this issue for now due to missing information. Feel free to get back to us with more details or a reproduction. Thanks!

**Closed by falkoschindler** 2024-06-28 06:00 UTC
Labels: question
