### ISSUE TITLE
I can't save chinese data in app.storage

### ISSUE THREAD

**Issue by SHDocter** [zauberzeug/nicegui#2163] opened 2023-12-13 05:44 UTC
### Description

1. I want use bind_value to save and read chinese data.
`ui.input(label="title").bind_value(app.storage.general, 'title')`
2.
3. Chinese data will garbled in storage_general.json, if use json module to save data, i can see gbk error when i use bind_value_from().

**Comment by falkoschindler** [comment] 2023-12-13 07:22
Hi @SHDocter!
That sounds bad. Could you, please, provide some example data that is producing the error? And could you show us the gbk error message? That would help reproducing and fixing this issue. Thanks!

**Comment by SHDocter** [comment] 2023-12-13 07:47
Sure!

This is gbk error.
![图片](https://github.com/zauberzeug/nicegui/assets/72510879/aaf10f05-610e-4478-821f-a929ae779863)

This is storage_general.json.
![图片](https://github.com/zauberzeug/nicegui/assets/72510879/ed5416eb-d740-4d14-9f1e-cee4ab617415)

This is code with use json module to save data.
![图片](https://github.com/zauberzeug/nicegui/assets/72510879/a053e4a6-26c0-4a2a-8530-40f1c6a5a291)

This is example code.
![图片](https://github.com/zauberzeug/nicegui/assets/72510879/84a5b52c-53ed-4726-b97f-d3e51a1a4c77)

Oh! I just find that if I manually change storage_general.json's data, it won't report gbk error, but it will still be garbled. I don't know if it's because when save data to json I used the ensure_ascii=False. I hope this will be helpful to you. Thanks!

Sorry, my english is bad...

**Comment by falkoschindler** [comment] 2023-12-14 16:05
@SHDocter Sorry, we can't reproduce any problem.

What are you trying to do with `save_config`? Why don't you simply write
```py
ui.input(label='title').bind_value(app.storage.general, 'title')
```

Does this single line work for you?

**Comment by SHDocter** [comment] 2023-12-15 03:22
I want to save chinese data from input to storage.
I tried again and now it can read chinese data, but when saving, the data in `storage_general.json` is still garbled

This is input.
![图片](https://github.com/zauberzeug/nicegui/assets/72510879/5101a1ab-70ba-45c1-9df8-e39afa303552)
![图片](https://github.com/zauberzeug/nicegui/assets/72510879/1f94e4b1-acf0-43a8-a4b5-5b37d5447b53)

This is storage_general.json.
![图片](https://github.com/zauberzeug/nicegui/assets/72510879/62d3c995-d261-4a3e-9d1f-432e973dbcc7)

This is what it displays.
![图片](https://github.com/zauberzeug/nicegui/assets/72510879/ea0cf201-8d14-4667-b652-0d0403bbf342)



But when I manually change the `storage_general.json` data to chinese characters, when I restart the program, it will report a GBK error
![图片](https://github.com/zauberzeug/nicegui/assets/72510879/f9d4651e-bcc2-4b49-8d53-54d9990a88b7)

Maybe it's because I use the Chinese Windows11 system? I have not tested it on other language systems or Win10.

It works, but I'm not sure if there will be any problems if it's given to users. If the problem cannot be reproduced or fixed, I can try not to use this feature.

Oh, I'm not blaming you, I just don't want to add too much work to you, thanks!

**Comment by rodja** [comment] 2023-12-15 03:46
For me, the following is working:

1. using the code `ui.input(label='title').bind_value(app.storage.general, 'title')`
2. opening the webpage and adding some Chinese characters in the input field
3. restarting the app -> the characters are still there
4. opening vscode and editing/saving `.nicegui/storage_general.json` to have some other Chinese characters
5. restarting the app -> the new characters are correctly showing

Maybe the problem lies in how you write the storage? Could you verify with vscode or some editor that the content you have written is correct?

**Comment by SHDocter** [comment] 2023-12-15 04:03
I am using vscode, but there will be GBK errors after I edit it.
Oh! I am using native=True, maybe there is a problem with this?

**Comment by falkoschindler** [comment] 2023-12-15 12:20
@SHDocter It sounds like NiceGUI is working correctly, but your VSCode reads/writes the JSON file with a wrong encoding. The file should be encoded with UTF-8. A different encoding would explain why the file _looks_ garbled and why NiceGUI struggles reading the file after you saved it with VSCode.

**Comment by SHDocter** [comment] 2023-12-15 16:43
My vscode's encoding is UTF-8, but when I change the encoding of the JSON I opened with vscode to GBK, the program can read and write chinese characters normally, and there will be no errors when I manually change the JSON.

I'm not sure why, but I can find a way to automatically change the JSON's encoding to GBK when the user uses it, after all, I can't be sure that the user can understand what encoding is.

Thank you very much for your help!

**Comment by SHDocter** [comment] 2023-12-15 16:51
I have been using vscode to run this program, and I am not sure if this is the reason. I will test if I use the `Python main. py` method to run it properly.

But it's currently midnight where I am, so I can't use my PC, but if there are any results, I will send a message!

**Comment by falkoschindler** [comment] 2023-12-15 16:59
Ah, I'm starting to understand:

1. NiceGUI stores the JSON file without specifying an encoding. ["The default encoding is platform dependent"](https://docs.python.org/3/library/functions.html#open), so it might be GBK on your machine.
2. VSCode seems to be set to UTF-8, so it can't read the file successfully.
3. When VSCode writes the file, it uses UTF-8, which doesn't work with NiceGUI, which assumes platform-dependent GBK.

So technically it isn't a bug in NiceGUI, since we don't promise any specific encoding. But maybe we should specify UTF-8 nonetheless. Explicitly setting the encoding is usually recommended.

But: Changing the encoding to UTF-8 can break the persistence of our users. Even if we do the change with a major release, how can we ensure a smooth transition without loosing all data? Maybe we need to change filenames to indicate the current encoding.

**Comment by SHDocter** [comment] 2023-12-15 17:10
Mayb it is possible to add a variable to specify encoding in `bind_value()` or other related functions?

Example: `ui.input(label="title").bind_value(app.storage.general, 'title', encoding='utf-8')`

Or can we refer to `setdefault()` ? It seems like this function, I'm sorry I don't quite remember.

Example: 
```
test.set_encoding('utf-8')
test = ui.input(label="title").bind_value(app.storage.general, 'title', encoding='utf-8')
```

Changing the file name is also a good idea!

**Comment by falkoschindler** [comment] 2023-12-17 14:07
@rodja I'd like to close this issue, because I don't see a problem in using the system's default encoding (GBK) when writing storage files. If the user views and edits these files with VSCode without setting the correct encoding, that's not a NiceGUI bug. Another editor could assume GBK and would have problems reading UTF-8. So it wouldn't help switching to UTF-8. It just would introduce compatibility problems. Do you agree?

**Comment by rodja** [comment] 2023-12-17 15:07
@falkoschindler I'm not so sure. What if a user changes the default encoding? It would break all the persistent data...

**Comment by falkoschindler** [comment] 2023-12-17 15:26
@rodja Oh, I didn't think about the possibility of changing the default encoding. But yes, that might be possible. So we should enforce UTF-8, but make sure to preserve compatibility with existing files.

**Closed** 2023-12-24 04:57 UTC
Labels: enhancement
