### ISSUE TITLE
RuntimeError: Directory 'static' does not exist

### ISSUE THREAD

**Issue by Quincy515** [zauberzeug/nicegui#1597] opened 2023-09-11 09:15 UTC
### Description

main.py

```python
from nicegui import app, ui

app.add_static_files('/static', 'static')

ui.query("body").style('background-image: url("static/bg.jpg");')

ui.run()
```

build.py

```python
import os
import subprocess
from pathlib import Path
import nicegui

cmd = [
    "PyInstaller",
    "main.py",  # your main file with ui.run()
    "--name",
    "myapp",  # name of your app
    "--onefile",
    "--windowed",  # prevent console appearing, only use with ui.run(native=True, ...)
    "--add-data",
    f"{Path(nicegui.__file__).parent}{os.pathsep}nicegui",
    "--add-data",
    "static/*;static",
]
subprocess.call(cmd)
```

error:

```shell
Traceback (most recent call last):
  File "main.py", line 3, in <module>
  File "nicegui\app.py", line 86, in add_static_files
    globals.app.mount(url_path, StaticFiles(directory=str(local_directory)))
  File "starlette\staticfiles.py", line 57, in __init__
RuntimeError: Directory 'static' does not exist
```

```shell
python -c 'import nicegui; print(nicegui.__version__)'
1.3.13
```

**Comment by meslahik** [comment] 2023-09-12 12:57
I suggest adding your 'static' directory similar to the way nicegui directory is added.
For example, if your build.py is alongside your static directory:
`"--add-data", f"{Path(__file__).parent.joinpath("static")}{os.pathsep}static"`

**Comment by CusterFun** [comment] 2023-09-13 01:16
> I suggest adding your 'static' directory similar to the way nicegui directory is added. For example, if your build.py is alongside your static directory: `"--add-data", f"{Path(__file__).parent.joinpath('static')}{os.pathsep}static"`

It's the same mistake

<img width="380" alt="image" src="https://github.com/zauberzeug/nicegui/assets/7986197/84a98dfb-3d32-4a7a-ac3f-66923e030f75">

**Comment by falkoschindler** [comment] 2023-09-18 08:41
Can anyone reproduce the problem? 🤞🏻

**Comment by sakelariev** [comment] 2023-10-06 14:19
I have encountered the same issue. 

**layout_test.py**

```python
from nicegui import app,native_mode, ui
import pandas as pd

app.add_static_files('/static', 'static')
# Empty table creation
seo = pd.read_csv("/static/df_test.csv", index_col=0)

# Let's round dataframe
ui.table(
    columns=[{'name': col, 'label': col, 'field': col, 'sortable': True} for col in seo.columns],
    rows=seo.to_dict('records'),
    pagination={'rowsPerPage': 10, 'sortBy': 'impressions', 'page': 1}
).props('dense').classes('w-full')

with ui.header(elevated=True).style('background-color: #3874c8').classes('items-center justify-between'):
    ui.label('HEADER')
    ui.button(on_click=lambda: right_drawer.toggle(), icon='menu').props('flat color=white')
with ui.left_drawer().style('background-color: #d7e3f4'):
    ui.label('LEFT DRAWER')
    
with ui.right_drawer(fixed=False).style('background-color: #ebf1fa').props('bordered') as right_drawer:
    ui.label('RIGHT DRAWER')

ui.run(reload=False,native=True, port=native_mode.find_open_port())
``` 

**build.py**

```python
import os
import subprocess
from pathlib import Path
import nicegui

cmd = [
    'python',
    '-m', 'PyInstaller',
    'layout_test.py',
    '--name', 'my_app', 
    '--onefile',
    '--windowed', 
    '--add-data', f'{Path(nicegui.__file__).parent}{os.pathsep}nicegui',
    '--add-data', f"{Path(__file__).parent.joinpath('static')}{os.pathsep}static"
    
]

subprocess.call(cmd)
``` 

**Error**
```shell
Traceback (most recent call last):
  File "layout_test.py", line 4, in <module>
  File "nicegui/app.py", line 88, in add_static_files
  File "starlette/staticfiles.py", line 57, in __init__
RuntimeError: Directory 'static' does not exist
[3033] Failed to execute script 'layout_test' due to unhandled exception: Directory 'static' does not exist
[3033] Traceback:
Traceback (most recent call last):
  File "layout_test.py", line 4, in <module>
  File "nicegui/app.py", line 88, in add_static_files
    globals.app.mount(url_path, StaticFiles(directory=str(local_directory)))
  File "starlette/staticfiles.py", line 57, in __init__
RuntimeError: Directory 'static' does not exist
``` 


I'm on a Mac **M1** with NiceGUI version **1.3.15**

**Comment by sakelariev** [comment] 2023-10-09 09:48
> Add the following line before subprocess.call():
> `print(f"{Path(__file__).parent.joinpath('static')}")`
> Can you confirm that static directory exists in that path?

Yes

> *What if you exclude the '--windowed' option? 
> Do you see the static directory inside `dist/my_app`?*

Again yes, however the static directory is inside another directory called `_internal`, so the path looks like this `dist/my_app/_internal/static`

I was able to successfully run my script, when I changed the way I load my .csv file from absolute path to `csv_file = f"{Path(**file**).parent.joinpath('static/df_test.csv')}"`

However this works with the `'--windowed’` option disabled, when I try to run the packaged app I get a constant loop of processes that are started and then die, but the app window is never displayed, it’s like something is preventing it from starting properly. When I remove any of my data loading code and just display the same UI, the app works and I get the app window (there are lot’s of processes started again).

Example code with data loaded (doesn’t work with '--windowed’ and  '-onefile’)
```python
from nicegui import app,native_mode, ui
import pandas as pd
from pathlib import Path

app.add_static_files('/static', 'static')
csv_file = f"{Path(__file__).parent.joinpath('static/df_test.csv')}"
df = pd.read_csv(csv_file, index_col=0)

df = df.round({'ctr': 2, 'avg_position': 1})
ui.table(
    columns=[{'name': col, 'label': col, 'field': col, 'sortable': True} for col in df.columns],
    rows=df.to_dict('records'),
    pagination={'rowsPerPage': 10, 'sortBy': 'impressions', 'page': 1}
).props('dense').classes('w-full')

with ui.header(elevated=True).style('background-color: #3874c8').classes('items-center justify-between'):
    ui.label('HEADER')
    ui.button(on_click=lambda: right_drawer.toggle(), icon='menu').props('flat color=white')
with ui.left_drawer().style('background-color: #d7e3f4'):
    ui.label('LEFT DRAWER')
    
with ui.right_drawer(fixed=False).style('background-color: #ebf1fa').props('bordered') as right_drawer:
    ui.label('RIGHT DRAWER')

ui.run(reload=False,native=True, port=native_mode.find_open_port())
``` 

Example code without any data loaded (works with '--windowed’ and  '-onefile’ )
```python
from nicegui import app,native_mode, ui

with ui.header(elevated=True).style('background-color: #3874c8').classes('items-center justify-between'):
    ui.label('HEADER')
    ui.button(on_click=lambda: right_drawer.toggle(), icon='menu').props('flat color=white')
with ui.left_drawer().style('background-color: #d7e3f4'):
    ui.label('LEFT DRAWER')
    
with ui.right_drawer(fixed=False).style('background-color: #ebf1fa').props('bordered') as right_drawer:
    ui.label('RIGHT DRAWER')

ui.run(reload=False,native=True, port=native_mode.find_open_port())
```

**Comment by sakelariev** [comment] 2023-10-12 08:56
Actually the issue seems to have been in setting the path for adding the static folder incorrectly. Once I've added the correct path it resolved. So besides in the build.py one must also use the correct parent directory in the app script as well.

To answer your original question @CusterFun , this is the right way to add the static_files folder:

**main.py**
```python
from nicegui import app, ui

app.add_static_files('/static', Path(__file__).parent.joinpath('static'))

ui.query("body").style('background-image: url("static/bg.jpg");')

ui.run()
``` 

and you also need to do the same for the **build.py** script as well, like described above.

**Comment by falkoschindler** [comment] 2023-11-08 06:00
This issue seems to be resolved. I'll close it.

**Closed by falkoschindler** 2023-11-08 06:00 UTC
Labels: help wanted
