### ISSUE TITLE
tortoise orm cannot work when I upgrade the version of nicegui to 1.4.x

### ISSUE THREAD

**Issue by hu76589** [zauberzeug/nicegui#1901] opened 2023-10-27 07:16 UTC
### Description

with nicegui 1.3.18,it works well:
```py
# models.py
from tortoise import fields, models

class Subject(models.Model):
    subject_id = fields.IntField(pk=True)
    subject_pid = fields.IntField()
    subject_code = fields.CharField(max_length=50)
    subject_name = fields.CharField(max_length=50)
    subject_dc = fields.CharField(max_length=1)
    is_expenses = fields.IntField()
    is_using = fields.IntField()
    is_query = fields.IntField()
    original_balance = fields.DecimalField(10, 2)
```

```py
# action.py
from tortoise.contrib.fastapi import register_tortoise
from nicegui import app

import models

register_tortoise(
    app,
    db_url='sqlite://books.sqlite3',
    modules={'models': ['models']},
    generate_schemas=False,
)

async def get_using_subjects_tree():
    # This line of code reported an error
    subjects = await models.Subject.filter(is_using = 1).order_by('subject_code')
    # do somethings...
```

but with 1.4.x, it cannot work, the error is:
```
default_connection for the model <class 'models.Subject'> cannot be None
```

**Comment by falkoschindler** [comment] 2023-10-27 07:30
Oh dear, it looks like tortoise isn't compatible with the new FastAPI lifespan API: https://github.com/tortoise/tortoise-orm/issues/1371. We upgraded in https://github.com/zauberzeug/nicegui/issues/1849 because the old API is deprecated. But other libraries still seem to be using it.

Maybe we can add support for both, FastAPI below 0.95.0 and above?

**Comment by falkoschindler** [comment] 2023-10-27 08:18
I found a workaround:

https://github.com/zauberzeug/nicegui/blob/58ab41a78bba784de94056d5550e64dbfb8104d9/examples/sqlite_database/main.py#L10-L19

This way we don't have to wait for https://github.com/tortoise/tortoise-orm/issues/1371. 🙂

**Comment by falkoschindler** [comment] 2023-10-27 09:06
Oh no, the solution causes an exception when closing the app on Python 3.11:

```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.11/site-packages/aiosqlite/core.py", line 109, in run
    get_loop(future).call_soon_threadsafe(set_result, future, result)
  File "uvloop/loop.pyx", line 1288, in uvloop.loop.Loop.call_soon_threadsafe
  File "uvloop/loop.pyx", line 671, in uvloop.loop.Loop._append_ready_handle
  File "uvloop/loop.pyx", line 703, in uvloop.loop.Loop._check_closed
RuntimeError: Event loop is closed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
    self.run()
  File "/opt/homebrew/lib/python3.11/site-packages/aiosqlite/core.py", line 117, in run
    get_loop(future).call_soon_threadsafe(set_exception, future, e)
  File "uvloop/loop.pyx", line 1288, in uvloop.loop.Loop.call_soon_threadsafe
  File "uvloop/loop.pyx", line 671, in uvloop.loop.Loop._append_ready_handle
  File "uvloop/loop.pyx", line 703, in uvloop.loop.Loop._check_closed
RuntimeError: Event loop is closed
```

This lets our startup test fail.

**Comment by falkoschindler** [comment] 2023-10-28 11:21
There is a related issue on aiosqlite: https://github.com/omnilib/aiosqlite/issues/241
I think we need to ignore this startup test for now, wait for the issue to be fixed upstream and re-activate it later.

**Comment by rodja** [comment] 2023-10-28 11:29
I'm fine with that. I've just tried to reproduce the problem locally. In most cases the demo exits normally. Maybe in 1 out of 10 cases I get the error.

**Comment by falkoschindler** [comment] 2023-10-28 11:38
Strange, it happens all the time on my machine.
Anyway, I just pushed a commit skipping this test on Python 3.11. Let's see if it passes.

**Comment by falkoschindler** [comment] 2023-10-28 11:40
After identifying https://github.com/tortoise/tortoise-orm/issues/1371 and https://github.com/omnilib/aiosqlite/issues/241 as root causes for existing problems with Tortoise, I'll close this issue.

**Closed by falkoschindler** 2023-10-28 11:40 UTC
Labels: documentation
