### ISSUE TITLE
multiprocessing 

### ISSUE THREAD

**Issue by AriBermeki** [zauberzeug/nicegui#1540] opened 2023-09-01 12:45 UTC
### Description

```py
from multiprocessing import  Manager, Process
import threading
from time import sleep
from enum import Enum
import numpy as np
import random 
from datetime import datetime
from nicegui import ui
from nicegui.events import ValueChangeEventArguments

class imp_data:                     #class data for locked sharing
    def __init__(self):
        self.file_name = 'name'
        self.probe_nr = '0'
        self.comments = 'no comment'
        self.u_min = 0.0
        self.u_max = 3.0
        self.delta_u = 0.2
        self.t_meas = 20000.0 #ms
        self.I    = 0.0
        self.U    = 0.0
        self.modus = 0
        self.SMachine = 0
        self.error = 0
        self.sig_sn = "0000"
        self.firmware = "V1.0"
        self.time_p    = 0.0
        self.progress = 0.0
    def server_data(self):
        data=np.array([self.SMachine,self.modus,self.error,self.progress,self.file_name,self.probe_nr,self.comments,self.u_min,self.u_max,self.delta_u,self.t_meas,self.I,self.U,self.time_p, self.sig_sn, self.firmware])
        return data

class SM(Enum):                     #Enum type
    INIT        = 0
    READY       = 1
    RUNNING     = 2
    MEASURING   = 3
    PAUSE       = 4
    STOP        = 5
    CANCEL      = 6

class S_DATA(Enum):                 #Enum type
    STATE_MACHINE   = 0
    MODUS           = 1
    ERROR           = 2
    PROGRESS        = 3
    FILE_NAME       = 4
    PROBE_NR        = 5 
    COMMENTS        = 6
    U_MIN           = 7 
    U_MAX           = 8
    DELTA_U         = 9 
    T_MEAS          = 10
    I               = 11 
    U               = 12
    TIME_P          = 13 
    SIG_SN          = 14
    FIRMWARE        = 15

class classMultiPros:
    def __init__(self):  
        self.init = 0
    
    def th(self, server_data):
        while True:
            SMach = int(server_data[S_DATA.STATE_MACHINE.value])
            if SMach == SM.INIT.value:
                print("vai")
                sleep(10)
                server_data[S_DATA.STATE_MACHINE.value] = SM.READY.value
            elif SMach == SM.RUNNING.value:
                sleep(2)
                server_data[S_DATA.STATE_MACHINE.value] = SM.MEASURING.value
            elif SMach == SM.MEASURING.value:
                sleep(10)
                server_data[S_DATA.STATE_MACHINE.value] = SM.STOP.value
            elif SMach == SM.CANCEL.value:
                sleep(10)
                server_data[S_DATA.STATE_MACHINE.value] = SM.READY.value
            elif SMach == SM.STOP.value:    
                sleep(10)
                server_data[S_DATA.STATE_MACHINE.value] = SM.READY.value
           
            server_data[S_DATA.I.value] = random.randint(0,10)
            server_data[S_DATA.U.value] = random.randint(0,10)
            sleep(1)

#if __name__ in {"__main__", "__mp_main__"}:     
if __name__ == "__main__":
    with Manager() as manager:
        #shared data Manages from intern class
        imp_data2 =imp_data()
        data = imp_data2.server_data()
        shared_list = manager.list(data)
        MultPros = classMultiPros()
        p1 = Process(target = MultPros.th, args=(shared_list,))
        p1.start() 
        sleep(3)
        #######################################SERVER CODE################################################################################################
        
        line_plot = ui.line_plot(n=2, limit=20, figsize=(3, 2), update_every=5) \
        .with_legend(['sin', 'cos'], loc='upper center', ncol=2)

        def btn_click() -> None:
            print("Btn clicked")
            if (shared_list[S_DATA.STATE_MACHINE.value]==SM.READY.value):
                shared_list[S_DATA.STATE_MACHINE.value] = SM.RUNNING.value

        def update_line_plot() -> None:
            now = datetime.now()
            x = now.timestamp()
            y1 = np.sin(x)
            y2 = np.cos(x)
            line_plot.push([now], [[float(shared_list[S_DATA.I.value])], [float(shared_list[S_DATA.U.value])]])
            print("I ",shared_list[S_DATA.I.value]," U ",shared_list[S_DATA.U.value],"SM ",shared_list[S_DATA.STATE_MACHINE.value])


        line_updates = ui.timer(0.1, update_line_plot, active=False)
        line_checkbox = ui.checkbox('active').bind_value(line_updates, 'active')
        ui.button('Start', on_click = btn_click)
        ui.button('Button', on_click= lambda: ui.notify('Click'))

        ui.run()
        p1.join()  
```

```
Desktop/FastAPI-SiC/venv/Scripts/python.exe c:/Users/MalekAli/Desktop/FastAPI-SiC/server/test_2.py
ERROR:    Traceback (most recent call last):
  File "FastAPI-SiC\venv\Lib\site-packages\starlette\routing.py", line 677, in lifespan
    async with self.lifespan_context(app) as maybe_state:
  File "FastAPI-SiC\venv\Lib\site-packages\starlette\routing.py", line 566, in __aenter__
    await self._router.startup()
  File "FastAPI-SiC\venv\Lib\site-packages\starlette\routing.py", line 656, in startup
    handler()
  File "Desktop\FastAPI-SiC\venv\Lib\site-packages\nicegui\nicegui.py", line 70, in handle_startup
    raise RuntimeError('\n\n'
RuntimeError:

You must call ui.run() to start the server.
If ui.run() is behind a main guard
   if __name__ == "__main__":
remove the guard or replace it with
   if __name__ in {"__main__", "__mp_main__"}:
to allow for multiprocessing.

ERROR:    Application startup failed. Exiting.
WARNING:  WatchFiles detected changes in 'server\test_2.py'. Reloading...
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "AppData\Local\Programs\Python\Python311\Lib\multiprocessing\spawn.py", line 120, in spawn_main
    exitcode = _main(fd, parent_sentinel)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "CAppData\Local\Programs\Python\Python311\Lib\multiprocessing\spawn.py", line 129, in _main
    prepare(preparation_data)
  File "C\AppData\Local\Programs\Python\Python311\Lib\multiprocessing\spawn.py", line 240, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "C:\Users\MalekAli\AppData\Local\Programs\Python\Python311\Lib\multiprocessing\spawn.py", line 291, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen runpy>", line 291, in run_path
  File "<frozen runpy>", line 98, in _run_module_code
  File "<frozen runpy>", line 88, in _run_code
  File "c:\Desktop\FastAPI-SiC\server\test_2.py", line 99, in <module>
    p1.start()
  File "C:\AppData\Local\Programs\Python\Python311\Lib\multiprocessing\process.py", line 121, in start
    self._popen = self._Popen(self)
                  ^^^^^^^^^^^^^^^^^
  File "C:\AppData\Local\Programs\Python\Python311\Lib\multiprocessing\context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\AppData\Local\Programs\Python\Python311\Lib\multiprocessing\context.py", line 336, in _Popen
    return Popen(process_obj)
           ^^^^^^^^^^^^^^^^^^
  File "C:\AppData\Local\Programs\Python\Python311\Lib\multiprocessing\popen_spawn_win32.py", line 45, in __init__
    prep_data = spawn.get_preparation_data(process_obj._name)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\AppData\Local\Programs\Python\Python311\Lib\multiprocessing\spawn.py", line 158, in get_preparation_data
    _check_not_importing_main()
  File "Local\Programs\Python\Python311\Lib\multiprocessing\spawn.py", line 138, in _check_not_importing_main
    raise RuntimeError('''
RuntimeError:
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
```

**Comment by natankeddem** [comment] 2023-09-02 02:30
You appear to have a bunch of syntax errors? All of the `__` are missing. This code works for me other than some connection errors related to your proprietary code I think.

```py
import random
import threading
from datetime import datetime
from enum import Enum
from multiprocessing import Manager, Process
from time import sleep

import numpy as np

from nicegui import ui
from nicegui.events import ValueChangeEventArguments


class imp_data:  # class data for locked sharing
    def __init__(self):
        self.file_name = 'name'
        self.probe_nr = '0'
        self.comments = 'no comment'
        self.u_min = 0.0
        self.u_max = 3.0
        self.delta_u = 0.2
        self.t_meas = 20000.0  # ms
        self.I = 0.0
        self.U = 0.0
        self.modus = 0
        self.SMachine = 0
        self.error = 0
        self.sig_sn = "0000"
        self.firmware = "V1.0"
        self.time_p = 0.0
        self.progress = 0.0

    def server_data(self):
        data = np.array([self.SMachine, self.modus, self.error, self.progress, self.file_name, self.probe_nr, self.comments,
                        self.u_min, self.u_max, self.delta_u, self.t_meas, self.I, self.U, self.time_p, self.sig_sn, self.firmware])
        return data


class SM(Enum):  # Enum type
    INIT = 0
    READY = 1
    RUNNING = 2
    MEASURING = 3
    PAUSE = 4
    STOP = 5
    CANCEL = 6


class S_DATA(Enum):  # Enum type
    STATE_MACHINE = 0
    MODUS = 1
    ERROR = 2
    PROGRESS = 3
    FILE_NAME = 4
    PROBE_NR = 5
    COMMENTS = 6
    U_MIN = 7
    U_MAX = 8
    DELTA_U = 9
    T_MEAS = 10
    I = 11
    U = 12
    TIME_P = 13
    SIG_SN = 14
    FIRMWARE = 15


class classMultiPros:
    def __init__(self):
        self.init = 0

    def th(self, server_data):
        while True:
            SMach = int(server_data[S_DATA.STATE_MACHINE.value])
            if SMach == SM.INIT.value:
                print("vai")
                sleep(10)
                server_data[S_DATA.STATE_MACHINE.value] = SM.READY.value
            elif SMach == SM.RUNNING.value:
                sleep(2)
                server_data[S_DATA.STATE_MACHINE.value] = SM.MEASURING.value
            elif SMach == SM.MEASURING.value:
                sleep(10)
                server_data[S_DATA.STATE_MACHINE.value] = SM.STOP.value
            elif SMach == SM.CANCEL.value:
                sleep(10)
                server_data[S_DATA.STATE_MACHINE.value] = SM.READY.value
            elif SMach == SM.STOP.value:
                sleep(10)
                server_data[S_DATA.STATE_MACHINE.value] = SM.READY.value

            server_data[S_DATA.I.value] = random.randint(0, 10)
            server_data[S_DATA.U.value] = random.randint(0, 10)
            sleep(1)


# if name in {"main", "mp_main"}:
# if name == "main":
if __name__ in {"__main__", "__mp_main__"}:
    with Manager() as manager:
        # shared data Manages from intern class
        imp_data2 = imp_data()
        data = imp_data2.server_data()
        shared_list = manager.list(data)
        MultPros = classMultiPros()
        p1 = Process(target=MultPros.th, args=(shared_list,))
        p1.start()
        sleep(3)
####################################### SERVER CODE################################################################################################

    line_plot = ui.line_plot(n=2, limit=20, figsize=(3, 2), update_every=5) \
        .with_legend(['sin', 'cos'], loc='upper center', ncol=2)

    def btn_click() -> None:
        print("Btn clicked")
        if (shared_list[S_DATA.STATE_MACHINE.value] == SM.READY.value):
            shared_list[S_DATA.STATE_MACHINE.value] = SM.RUNNING.value

    def update_line_plot() -> None:
        now = datetime.now()
        x = now.timestamp()
        y1 = np.sin(x)
        y2 = np.cos(x)
        line_plot.push([now], [[float(shared_list[S_DATA.I.value])], [float(shared_list[S_DATA.U.value])]])
        print("I ", shared_list[S_DATA.I.value], " U ", shared_list[S_DATA.U.value],
              "SM ", shared_list[S_DATA.STATE_MACHINE.value])

    line_updates = ui.timer(0.1, update_line_plot, active=False)
    line_checkbox = ui.checkbox('active').bind_value(line_updates, 'active')
    ui.button('Start', on_click=btn_click)
    ui.button('Button', on_click=lambda: ui.notify('Click'))

    ui.run()
    p1.join()
```

**Comment by AriBermeki** [comment] 2023-09-02 06:09
![Screenshot 2023-09-02 080744](https://github.com/zauberzeug/nicegui/assets/90009669/bf6eee0b-b040-422f-8944-469d7c8a0bd7)

**Comment by AriBermeki** [comment] 2023-09-02 06:10
I just did copy paste

**Comment by AriBermeki** [comment] 2023-09-02 06:22
![image](https://github.com/zauberzeug/nicegui/assets/90009669/bd7c1c9c-4b1d-448d-8079-e55114914027)

**Comment by AriBermeki** [comment] 2023-09-02 06:23
the picture before that is on windows this picture on mac

**Comment by natankeddem** [comment] 2023-09-02 12:03
Sorry, like I said with the code I cleaned up I don't get the error. Maybe someone else can try running the code I posted?

**Comment by rodja** [comment] 2023-09-02 12:05
@AriBermeki do you get the error with exactly the code which @natankeddem posted in https://github.com/zauberzeug/nicegui/issues/1540#issuecomment-1703651730?

**Comment by AriBermeki** [comment] 2023-09-02 14:45
Yes Rodja, I just copied and pasted even though I had the same code before

**Comment by rodja** [comment] 2023-09-03 03:18
@natankeddem 

> Sorry, like I said with the code I cleaned up I don't get the error. Maybe someone else can try running the code I posted?

I get the same error as @AriBermeki. 

@AriBermeki you could try with `ui.run(relaod=False)` in combination with `if __name__ == "__main__"` as main guard. If this does not help I would like you to create a minimal example which reproduces the error. All this Enums, imp_data, plotting etc is standing in the way of analyzing the problem effectively.

**Comment by natankeddem** [comment] 2023-09-03 12:53
The only errors I was getting was the following:
```
(venv)  python main.py
vai
vai
Process Process-2:
Traceback (most recent call last):
  File "/usr/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/natan/ngr0/main.py", line 78, in th
    server_data[S_DATA.STATE_MACHINE.value] = SM.READY.value
  File "<string>", line 2, in __setitem__
  File "/usr/lib/python3.10/multiprocessing/managers.py", line 817, in _callmethod
    conn.send((self._id, methodname, args, kwds))
  File "/usr/lib/python3.10/multiprocessing/connection.py", line 206, in send
    self._send_bytes(_ForkingPickler.dumps(obj))
  File "/usr/lib/python3.10/multiprocessing/connection.py", line 411, in _send_bytes
    self._send(header + buf)
  File "/usr/lib/python3.10/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
Process Process-2:
Traceback (most recent call last):
  File "/usr/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/natan/ngr0/main.py", line 78, in th
    server_data[S_DATA.STATE_MACHINE.value] = SM.READY.value
  File "<string>", line 2, in __setitem__
  File "/usr/lib/python3.10/multiprocessing/managers.py", line 817, in _callmethod
    conn.send((self._id, methodname, args, kwds))
  File "/usr/lib/python3.10/multiprocessing/connection.py", line 206, in send
    self._send_bytes(_ForkingPickler.dumps(obj))
  File "/usr/lib/python3.10/multiprocessing/connection.py", line 411, in _send_bytes
    self._send(header + buf)
  File "/usr/lib/python3.10/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
NiceGUI ready to go on http://localhost:8080, and http://127.0.1.1:8080 (install netifaces to show all IPs and speedup this message)
Btn clicked
[Errno 2] No such file or directory
Traceback (most recent call last):
  File "/usr/lib/python3.10/multiprocessing/managers.py", line 810, in _callmethod
    conn = self._tls.connection
AttributeError: 'ForkAwareLocal' object has no attribute 'connection'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/natan/ngr0/venv/lib/python3.10/site-packages/nicegui/events.py", line 383, in handle_event
    result = handler(arguments) if expects_arguments else handler()
  File "/home/natan/ngr0/main.py", line 116, in btn_click
    if (shared_list[S_DATA.STATE_MACHINE.value] == SM.READY.value):
  File "<string>", line 2, in __getitem__
  File "/usr/lib/python3.10/multiprocessing/managers.py", line 814, in _callmethod
    self._connect()
  File "/usr/lib/python3.10/multiprocessing/managers.py", line 801, in _connect
    conn = self._Client(self._token.address, authkey=self._authkey)
  File "/usr/lib/python3.10/multiprocessing/connection.py", line 502, in Client
    c = SocketClient(address)
  File "/usr/lib/python3.10/multiprocessing/connection.py", line 630, in SocketClient
    s.connect(address)
FileNotFoundError: [Errno 2] No such file or directory
```
Nothing about guarding so I am guessing it is something to do with some code looking for something missing from my environment which would be expected. Despite these errors I do get a working website with graph and buttons visible. Here is some context for my environment, running on W10 WSL2 debian:
```
## python --version
Python 3.10.12
## cat /etc/debian_version
bookworm/sid
## pip freeze
aiofiles==23.2.1
aiohttp==3.8.5
aiosignal==1.3.1
annotated-types==0.5.0
anyio==3.7.1
async-timeout==4.0.3
attrs==23.1.0
bidict==0.22.1
certifi==2023.7.22
charset-normalizer==3.2.0
click==8.1.7
contourpy==1.1.0
cycler==0.11.0
exceptiongroup==1.1.3
fastapi==0.103.1
fastapi-socketio==0.0.10
fonttools==4.42.1
frozenlist==1.4.0
h11==0.14.0
httpcore==0.17.3
httptools==0.6.0
httpx==0.24.1
idna==3.4
itsdangerous==2.1.2
Jinja2==3.1.2
kiwisolver==1.4.5
markdown2==2.4.10
MarkupSafe==2.1.3
matplotlib==3.7.2
multidict==6.0.4
nicegui==1.3.13
numpy==1.25.2
orjson==3.9.5
packaging==23.1
Pillow==10.0.0
pscript==0.7.7
pydantic==2.3.0
pydantic_core==2.6.3
Pygments==2.16.1
pyparsing==3.0.9
python-dateutil==2.8.2
python-dotenv==1.0.0
python-engineio==4.6.1
python-multipart==0.0.6
python-socketio==5.8.0
PyYAML==6.0.1
six==1.16.0
sniffio==1.3.0
starlette==0.27.0
typing_extensions==4.7.1
uvicorn==0.22.0
uvloop==0.17.0
vbuild==0.8.2
watchfiles==0.20.0
websockets==11.0.3
yarl==1.9.2
```

**Comment by falkoschindler** [comment] 2023-09-15 10:22
@natankeddem I just cleaned up the original post and added proper syntax highlighting. It turns out you changed the indentation of `ui.run`. That might explain the different behavior.

@AriBermeki Can you, please, reduce your code to a [minimum reproducible example](https://en.wikipedia.org/wiki/Minimal_reproducible_example)? In it's current form it's just too confusing and I'm not sure what you're actually trying to do.

**Comment by AriBermeki** [comment] 2023-09-15 11:53
It was noticed that there was an indentation error. However, you may not have noticed this either.   😂🤣🤣🤣

**Comment by AriBermeki** [comment] 2023-09-15 11:53
from multiprocessing import  Manager, Process
import threading
from time import sleep
from enum import Enum
import numpy as np
import random 
from datetime import datetime
from nicegui import ui
from nicegui.events import ValueChangeEventArguments

class imp_data:                     #class data for locked sharing
    def __init__(self):
        self.file_name = 'name'
        self.probe_nr = '0'
        self.comments = 'no comment'
        self.u_min = 0.0
        self.u_max = 3.0
        self.delta_u = 0.2
        self.t_meas = 20000.0 #ms
        self.I    = 0.0
        self.U    = 0.0
        self.modus = 0
        self.SMachine = 0
        self.error = 0
        self.sig_sn = "0000"
        self.firmware = "V1.0"
        self.time_p    = 0.0
        self.progress = 0.0
    def server_data(self):
        data=np.array([self.SMachine,self.modus,self.error,self.progress,self.file_name,self.probe_nr,self.comments,self.u_min,self.u_max,self.delta_u,self.t_meas,self.I,self.U,self.time_p, self.sig_sn, self.firmware])
        return data

class SM(Enum):                     #Enum type
    INIT        = 0
    READY       = 1
    RUNNING     = 2
    MEASURING   = 3
    PAUSE       = 4
    STOP        = 5
    CANCEL      = 6

class S_DATA(Enum):                 #Enum type
    STATE_MACHINE   = 0
    MODUS           = 1
    ERROR           = 2
    PROGRESS        = 3
    FILE_NAME       = 4
    PROBE_NR        = 5 
    COMMENTS        = 6
    U_MIN           = 7 
    U_MAX           = 8
    DELTA_U         = 9 
    T_MEAS          = 10
    I               = 11 
    U               = 12
    TIME_P          = 13 
    SIG_SN          = 14
    FIRMWARE        = 15

class classMultiPros:
    def __init__(self):  
        self.init = 0
    
    def th(self, server_data):
        while True:
            SMach = int(server_data[S_DATA.STATE_MACHINE.value])
            if SMach == SM.INIT.value:
                print("vai")
                sleep(3)
                server_data[S_DATA.STATE_MACHINE.value] = SM.READY.value
            elif SMach == SM.RUNNING.value:
                sleep(2)
                server_data[S_DATA.STATE_MACHINE.value] = SM.MEASURING.value
            elif SMach == SM.MEASURING.value:
                sleep(10)
                server_data[S_DATA.STATE_MACHINE.value] = SM.STOP.value
            elif SMach == SM.CANCEL.value:
                sleep(10)
                server_data[S_DATA.STATE_MACHINE.value] = SM.READY.value
            elif SMach == SM.STOP.value:    
                sleep(10)
                server_data[S_DATA.STATE_MACHINE.value] = SM.READY.value
           
            server_data[S_DATA.I.value] = random.randint(0,10)
            server_data[S_DATA.U.value] = random.randint(0,10)
            sleep(1)

   
if __name__ == "__main__":
    with Manager() as manager:
        # shared data Manages from intern class
        imp_data2 = imp_data()
        data = imp_data2.server_data()
        shared_list = manager.list(data)
        MultPros = classMultiPros()
        p1 = Process(target=MultPros.th, args=(shared_list,))
        p1.start()
        sleep(3)
####################################### SERVER CODE################################################################################################

        line_plot = ui.line_plot(n=2, limit=20, figsize=(3, 2), update_every=5) \
            .with_legend(['sin', 'cos'], loc='upper center', ncol=2)

        def btn_click() -> None:
            print("Btn clicked")
            if (shared_list[S_DATA.STATE_MACHINE.value] == SM.READY.value):
                shared_list[S_DATA.STATE_MACHINE.value] = SM.RUNNING.value

        def update_line_plot() -> None:
            now = datetime.now()
            x = now.timestamp()
            y1 = np.sin(x)
            y2 = np.cos(x)
            line_plot.push([now], [[float(shared_list[S_DATA.I.value])], [float(shared_list[S_DATA.U.value])]])
            print("I ", shared_list[S_DATA.I.value], " U ", shared_list[S_DATA.U.value],
                "SM ", shared_list[S_DATA.STATE_MACHINE.value])

        line_updates = ui.timer(0.1, update_line_plot, active=False)
        line_checkbox = ui.checkbox('active').bind_value(line_updates, 'active')
        ui.button('Start', on_click=btn_click)
        ui.button('Button', on_click=lambda: ui.notify('Click'))

        ui.run(reload=False)
        p1.join()

        #######################################SERVER CODE################################################################################################

**Comment by AriBermeki** [comment] 2023-09-15 11:53
https://github.com/zauberzeug/nicegui/assets/90009669/1b38cf8b-e2c0-4cdd-9998-d6ed982de6d5

**Comment by AriBermeki** [comment] 2023-09-15 11:55
I solved the problem

**Comment by AriBermeki** [comment] 2023-09-15 12:06
@falkoschindler The main aim of my project is to have time critical data akquisition separated from processes that are minor important. Therefore I have a state machine running that controls every measuring device connected to my Raspi. In order to access the raspi in our network we would like to use a webserver environment as GUI. The numbers shown in the terminal represent states and dummy measurement data. It is more or less a minimal version or our code without any hardware. Thank you for your support.

**Comment by natankeddem** [comment] 2023-09-15 13:19
> @natankeddem I just cleaned up the original post and added proper syntax highlighting. It turns out you changed the indentation of `ui.run`. That might explain the different behavior.

To be fair the code wasn't even fully contained in the code block and I was just taking guesses at intended indentation. That is why I asked others to run my "translation" to see if it gave the same errors; because it didn't for me. I have a feeling like @AriBermeki has some sort of copy/paste issue on their computer or something weird going on? Why were all the `__` missing from the original code? Perhaps they couldn't even try the code I provided by copy and pasting it?

**Comment by falkoschindler** [comment] 2023-09-15 14:02
@natankeddem Sorry, in case I sounded a bit negatively: I didn't mean to criticize your attempt at shedding light into this problem. I _really_ appreciate the effort you're putting into contributing to the project! Trying to find some common ground for reproducing the bug was just the right thing to do. ❤️

The reason why you didn't see the underscores is that without wrapping Python code into proper code blocks, double-underscores are interpreted as the Markdown code for bold text. Therefore `__init__` turns into __init__. As a maintainer I can simply look into the unrendered Markdown code (and edit the post right away). But I guess this not possible for everyone else.

It shows once again: A clear problem statement with a good and well-formatted code example is crucial. If this is not given, many contributors might run around in circles for days.

Let's close this thread, since the original problem seems to be resolved. 🤷‍♂️

**Closed by falkoschindler** 2023-09-15 14:02 UTC
Labels: question

**Comment by AriBermeki** [comment] 2023-09-15 14:26
@falkoschindler  Sorry, that was my mistake, this bug was my first bug report on Github 💚🤗🥳😂
