### ISSUE TITLE
nicegui failed to establish connection in docker

### ISSUE THREAD

**Issue by ipa-rar** [zauberzeug/nicegui#1214] opened 2023-07-21 11:40 UTC
### Description

I am using nicegui to make a UI for a FastAPI application, which fetches data from the influxDB. I am able to run the app natively on the system without any issues, however, when I run the application on docker I get an error. 
```
Attaching to nicegui
nicegui    | Traceback (most recent call last):
nicegui    |   File "/usr/local/lib/python3.11/site-packages/urllib3/connection.py", line 203, in _new_conn
nicegui    |     sock = connection.create_connection(
nicegui    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
nicegui    |   File "/usr/local/lib/python3.11/site-packages/urllib3/util/connection.py", line 85, in create_connection
nicegui    |     raise err
nicegui    |   File "/usr/local/lib/python3.11/site-packages/urllib3/util/connection.py", line 73, in create_connection
nicegui    |     sock.connect(sa)
nicegui    | ConnectionRefusedError: [Errno 111] Connection refused
nicegui    | 
nicegui    | The above exception was the direct cause of the following exception:
nicegui    | 
nicegui    | Traceback (most recent call last):
nicegui    |   File "/usr/local/bin/uvicorn", line 8, in <module>
nicegui    |     sys.exit(main())
nicegui    |              ^^^^^^
nicegui    |   File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
nicegui    |     return self.main(*args, **kwargs)
nicegui    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^
nicegui    |   File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1078, in main
nicegui    |     rv = self.invoke(ctx)
nicegui    |          ^^^^^^^^^^^^^^^^
nicegui    |   File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
nicegui    |     return ctx.invoke(self.callback, **ctx.params)
nicegui    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
nicegui    |   File "/usr/local/lib/python3.11/site-packages/click/core.py", line 783, in invoke
nicegui    |     return __callback(*args, **kwargs)
nicegui    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
nicegui    |   File "/usr/local/lib/python3.11/site-packages/uvicorn/main.py", line 410, in main
nicegui    |     run(
nicegui    |   File "/usr/local/lib/python3.11/site-packages/uvicorn/main.py", line 578, in run
nicegui    |     server.run()
nicegui    |   File "/usr/local/lib/python3.11/site-packages/uvicorn/server.py", line 61, in run
nicegui    |     return asyncio.run(self.serve(sockets=sockets))
nicegui    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
nicegui    |   File "/usr/local/lib/python3.11/asyncio/runners.py", line 190, in run
nicegui    |     return runner.run(main)
nicegui    |            ^^^^^^^^^^^^^^^^
nicegui    |   File "/usr/local/lib/python3.11/asyncio/runners.py", line 118, in run
nicegui    |     return self._loop.run_until_complete(task)
nicegui    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
nicegui    |   File "uvloop/loop.pyx", line 1517, in uvloop.loop.Loop.run_until_complete
nicegui    |   File "/usr/local/lib/python3.11/site-packages/uvicorn/server.py", line 68, in serve
nicegui    |     config.load()
nicegui    |   File "/usr/local/lib/python3.11/site-packages/uvicorn/config.py", line 473, in load
nicegui    |     self.loaded_app = import_from_string(self.app)
nicegui    |                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
nicegui    |   File "/usr/local/lib/python3.11/site-packages/uvicorn/importer.py", line 21, in import_from_string
nicegui    |     module = importlib.import_module(module_str)
nicegui    |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
nicegui    |   File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
nicegui    |     return _bootstrap._gcd_import(name[level:], package, level)
nicegui    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
nicegui    |   File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
nicegui    |   File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
nicegui    |   File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
nicegui    |   File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
nicegui    |   File "<frozen importlib._bootstrap_external>", line 940, in exec_module
nicegui    |   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
nicegui    |   File "/src/view/rokitAPI/main.py", line 8, in <module>
nicegui    |     results = read_influxdb.read()
nicegui    |               ^^^^^^^^^^^^^^^^^^^^
nicegui    |   File "/src/database/read_influxdb.py", line 31, in read
nicegui    |     result = query_api.query(org=org, query=query)
nicegui    |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
nicegui    |   File "/usr/local/lib/python3.11/site-packages/influxdb_client/client/query_api.py", line 203, in query
nicegui    |     response = self._query_api.post_query(org=org, query=self._create_query(query, self.default_dialect, params),
nicegui    |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
nicegui    |   File "/usr/local/lib/python3.11/site-packages/influxdb_client/service/query_service.py", line 279, in post_query
nicegui    |     (data) = self.post_query_with_http_info(**kwargs)  # noqa: E501
nicegui    |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
nicegui    |   File "/usr/local/lib/python3.11/site-packages/influxdb_client/service/query_service.py", line 305, in post_query_with_http_info
nicegui    |     return self.api_client.call_api(
nicegui    |            ^^^^^^^^^^^^^^^^^^^^^^^^^
nicegui    |   File "/usr/local/lib/python3.11/site-packages/influxdb_client/_sync/api_client.py", line 343, in call_api
nicegui    |     return self.__call_api(resource_path, method,
nicegui    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
nicegui    |   File "/usr/local/lib/python3.11/site-packages/influxdb_client/_sync/api_client.py", line 173, in __call_api
nicegui    |     response_data = self.request(
nicegui    |                     ^^^^^^^^^^^^^
nicegui    |   File "/usr/local/lib/python3.11/site-packages/influxdb_client/_sync/api_client.py", line 388, in request
nicegui    |     return self.rest_client.POST(url,
nicegui    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^
nicegui    |   File "/usr/local/lib/python3.11/site-packages/influxdb_client/_sync/rest.py", line 311, in POST
nicegui    |     return self.request("POST", url,
nicegui    |            ^^^^^^^^^^^^^^^^^^^^^^^^^
nicegui    |   File "/usr/local/lib/python3.11/site-packages/influxdb_client/_sync/rest.py", line 186, in request
nicegui    |     r = self.pool_manager.request(
nicegui    |         ^^^^^^^^^^^^^^^^^^^^^^^^^^
nicegui    |   File "/usr/local/lib/python3.11/site-packages/urllib3/_request_methods.py", line 118, in request
nicegui    |     return self.request_encode_body(
nicegui    |            ^^^^^^^^^^^^^^^^^^^^^^^^^
nicegui    |   File "/usr/local/lib/python3.11/site-packages/urllib3/_request_methods.py", line 217, in request_encode_body
nicegui    |     return self.urlopen(method, url, **extra_kw)
nicegui    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
nicegui    |   File "/usr/local/lib/python3.11/site-packages/urllib3/poolmanager.py", line 443, in urlopen
nicegui    |     response = conn.urlopen(method, u.request_uri, **kw)
nicegui    |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
nicegui    |   File "/usr/local/lib/python3.11/site-packages/urllib3/connectionpool.py", line 844, in urlopen
nicegui    |     retries = retries.increment(
nicegui    |               ^^^^^^^^^^^^^^^^^^
nicegui    |   File "/usr/local/lib/python3.11/site-packages/urllib3/util/retry.py", line 445, in increment
nicegui    |     raise reraise(type(error), error, _stacktrace)
nicegui    |           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
nicegui    |   File "/usr/local/lib/python3.11/site-packages/urllib3/util/util.py", line 39, in reraise
nicegui    |     raise value
nicegui    |   File "/usr/local/lib/python3.11/site-packages/urllib3/connectionpool.py", line 790, in urlopen
nicegui    |     response = self._make_request(
nicegui    |                ^^^^^^^^^^^^^^^^^^^
nicegui    |   File "/usr/local/lib/python3.11/site-packages/urllib3/connectionpool.py", line 496, in _make_request
nicegui    |     conn.request(
nicegui    |   File "/usr/local/lib/python3.11/site-packages/urllib3/connection.py", line 395, in request
nicegui    |     self.endheaders()
nicegui    |   File "/usr/local/lib/python3.11/http/client.py", line 1281, in endheaders
nicegui    |     self._send_output(message_body, encode_chunked=encode_chunked)
nicegui    |   File "/usr/local/lib/python3.11/http/client.py", line 1041, in _send_output
nicegui    |     self.send(msg)
nicegui    |   File "/usr/local/lib/python3.11/http/client.py", line 979, in send
nicegui    |     self.connect()
nicegui    |   File "/usr/local/lib/python3.11/site-packages/urllib3/connection.py", line 243, in connect
nicegui    |     self.sock = self._new_conn()
nicegui    |                 ^^^^^^^^^^^^^^^^
nicegui    |   File "/usr/local/lib/python3.11/site-packages/urllib3/connection.py", line 218, in _new_conn
nicegui    |     raise NewConnectionError(
nicegui    | urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f9aa3c9b550>: Failed to establish a new connection: [Errno 111] Connection refused
nicegui exited with code 1
```
Is there anything I should take care when making a docker container with nicegui.

**Comment by rodja** [comment] 2023-07-24 04:20
It does not look like a NiceGUI issue but a connection error to your influxdb. Can you ping the influxdb-server from within the Docker container? Double-Check the connection url.

**Comment by falkoschindler** [comment] 2023-08-02 09:40
I'll close this issue, since it doesn't seem to be caused by NiceGUI. Feel free to re-open it if you think otherwise.

**Closed by falkoschindler** 2023-08-02 09:40 UTC
Labels: question
