### ISSUE TITLE
ui.select with multiple=True closes the dialog

### ISSUE THREAD

**Issue by pythonormen** [zauberzeug/nicegui#1108] opened 2023-06-29 08:09 UTC
### Description

```python
from nicegui import ui

@ui.page('/')
async def index():
    async def admin():
        # Some processing
        dialog.open()

    with ui.button('Menu', on_click=lambda: menu_user.open()):
        with ui.menu() as menu_user:
            ui.menu_item('Admin', on_click=admin, auto_close=False)
            with ui.dialog() as dialog, ui.card():
                ui.label('Some text')
                ui.select(['One', 'Two', 'Three'], multiple=True)

                ui.label('Some additional text')
                ui.select(['One', 'Two', 'Three'])

ui.run(host="127.0.0.1")
```
ui.select with multiple=True closes the dialog after selection , if the selection "ends" by pressing on the dialog. Works as expected without multiple

I think it works if menu is not used. Don't see the same behaviour on my other ui.select's with multiple.

**Comment by falkoschindler** [comment] 2023-06-29 09:00
Interesting observation, @pythonormen!

What seems to happen is that the dialog's select element closes the menu when loosing focus. Because the dialog is nested within the menu, it is hidden when the menu closes. This could well be normal Quasar behavior, but I'm not sure.

One way to work around would be to define the dialog outside the menu:

```py
with ui.dialog() as dialog, ui.card():
    ui.label('Some text')
    ui.select(['One', 'Two', 'Three'], multiple=True)

    ui.label('Some additional text')
    ui.select(['One', 'Two', 'Three'])

with ui.button('Menu', on_click=lambda: menu_user.open()):
    with ui.menu() as menu_user:
        ui.menu_item('Admin', on_click=lambda: dialog.open(), auto_close=False)
```

But the menu itself closes when the multi-select looses focus. I guess this is normal, because usually only one dropdown is shown. I even wonder why it doesn't close when using the single-select. Is it important for your application to keep the menu open?

**Comment by pythonormen** [comment] 2023-06-29 09:07
I can work around it, no problem. Was just a bit surprised that it was different behaviour compared to single. Thanks

**Comment by falkoschindler** [comment] 2023-06-29 13:29
Ok, since the detailed explanation for the unexpected behavior probably lies somewhere deep inside Vue/Quasar, I'll close this issue on our side.

**Closed** 2023-06-29 13:30 UTC
Labels: wontfix
