### ISSUE TITLE
Value of clearable input is not yet updated in "clear" event handler

### ISSUE THREAD

**Issue by iron3oxide** [zauberzeug/nicegui#2242] opened 2023-12-26 06:55 UTC
### Description

```python
from nicegui import ui

def input():
    def cleared():
        print(i.value)

    i = ui.input("Test").props("clearable").on("clear", cleared)
```

**Expected behaviour**: The value of `i` is `""`
**Actual behaviour**: The value of `i` is whatever one had typed in before pressing the clear button 
**Workaround**:
```python
from nicegui import ui

def input():
    def cleared():
        i.set_value("")
        print(i.value)

    i = ui.input("Test").props("clearable").on("clear", cleared)
```

**Comment by iron3oxide** [comment] 2023-12-26 07:11
Just realized that this is probably a matter of preference: does one assume that a "clear" event should mean the value has already been cleared/set to an empty string and that handlers which need the old value can get it from the event args (my assumption)? Or does one assume that the actual clearing happens after this event has been handled (which is the case now). I'd argue that the latter is worse because it doesn't allow for easy customization of clear button behaviour.

**Comment by falkoschindler** [comment] 2023-12-26 10:05
Thanks for reporting this unexpected behavior, @iron3oxide!

But according to [Quasar's QInput documentation](https://quasar.dev/vue-components/input) this is what "clear" is supposed to do:

> value: Any
> Description
> The previous value before clearing it

It somehow makes sense, because the value after clearing is always `None`, so there is no point in transmitting it. And the name of the event is "clear" and not "cleared", which indicates that it is sent before the value is actually cleared.

Anyway, I'll close this issue as we won't be able and willing to change this behavior.

**Closed by falkoschindler** 2023-12-26 10:05 UTC
