### ISSUE TITLE
cdn.tailwindcss.com sould not be used in production error. 

### ISSUE THREAD

**Issue by muratbedir** [zauberzeug/nicegui#1879] opened 2023-10-25 14:22 UTC
### Description

When enter edge debug I see below error. Is it important error or just skip it? 

![image](https://github.com/zauberzeug/nicegui/assets/48950062/757eede2-18c8-4e24-be31-9828bd1ab3ff)

**Comment by falkoschindler** [comment] 2023-10-25 15:12
This is a duplicate of https://github.com/zauberzeug/nicegui/issues/337.
There you can find our opinion about this log message (which isn't an error by the way): Yes, you can ignore it.

**Closed by falkoschindler** 2023-10-25 15:12 UTC
