### ISSUE TITLE
globals.config is None in page.py

### ISSUE THREAD

**Issue by plassma** [zauberzeug/nicegui#183] opened 2022-11-26 12:07 UTC
Hello, I always get the following error when running the usage example from the readme and leaving `reload=True`:

```
ERROR:    Traceback (most recent call last):
  File "/home/plassma/miniconda3/envs/richi-bot/lib/python3.10/site-packages/starlette/routing.py", line 671, in lifespan
    async with self.lifespan_context(app):
  File "/home/plassma/miniconda3/envs/richi-bot/lib/python3.10/site-packages/starlette/routing.py", line 566, in __aenter__
    await self._router.startup()
  File "/home/plassma/miniconda3/envs/richi-bot/lib/python3.10/site-packages/starlette/routing.py", line 650, in startup
    handler()
  File "/home/plassma/miniconda3/envs/richi-bot/lib/python3.10/site-packages/nicegui/nicegui.py", line 36, in startup
    create_favicon_routes()
  File "/home/plassma/miniconda3/envs/richi-bot/lib/python3.10/site-packages/nicegui/page.py", line 330, in create_favicon_routes
    if globals.config.favicon:
AttributeError: 'NoneType' object has no attribute 'favicon'
```

`globals.config` is initialized in run.py:35, but `None` when accessed in other files (probably only other threads?).

Ubuntu 22, wayland, py 3.10, nicegui 0.9.25 (but tried back to 0.9.0, error is always that `globals.config` is `None`).

If I run with `reload=False`, I don't get the error

**Comment by falkoschindler** [comment] 2022-11-28 06:41
Thanks for reporting this issue!
I am, however, having difficulties reproducing the error on my Mac. It could be related to how Uvicorn creates new processes when auto-reloading the app. This is different on Mac and Linux: https://docs.python.org/3/library/multiprocessing.html#contexts-and-start-methods. But we regularly run NiceGUI apps on Linux machines without such problems. So there must be another difference.

**Comment by falkoschindler** [comment] 2022-11-28 06:45
@plassma Is it possible that you run your script with a main guard like in https://github.com/zauberzeug/nicegui/issues/181? This would result in exactly your error and stack trace.

**Comment by falkoschindler** [comment] 2022-12-15 14:52
I'll close this issue since the reproduction is unclear and things are different in NiceGUI 1.0 anyway.

**Closed by falkoschindler** 2022-12-15 14:52 UTC
Labels: question
