### ISSUE TITLE
PyInstaller not found

### ISSUE THREAD

**Issue by hrauch** [zauberzeug/nicegui#2549] opened 2024-02-13 11:03 UTC
### Description

I installed nicegui, pyinstaller and pywebview in a virtual environment with Python 3.12 and Windows 11. 
Trying your example on **https://nicegui.io/documentation/section_configuration_deployment** I get this error message:
**C:\Program Files\Python312\python.exe: No module named PyInstaller**
If I change the last line of your build.py script in
**subprocess.call(cmd, shell=True)**
everything is ok. May be that this modification is only needed with Windows 11.

**Comment by falkoschindler** [comment] 2024-02-19 09:32
Thanks for reporting this issue @hrauch!

Can anyone with Windows 11 reproduce the problem? Should we simply add `shell=True`?

**Comment by JS-Aibel** [comment] 2024-03-20 09:46
Not able to reproduce the problem.
Example [Configuration & Deployment | NiceGUI](https://nicegui.io/documentation/section_configuration_deployment#package_for_installation) OK for Windows 11.
I have nicegui and pyinstaller installed, not pywebview.

**Comment by alimate2023** [comment] 2024-03-22 22:58
If I use my virtual environment, it says I can't find the package. Try installing pyinstall and packaging it without the virtual environment.

**Comment by gotev** [comment] 2024-03-27 20:23
Been able to reproduce that on Windows 10 running a Python 3.12.2 virtual envronment and to find a solution. My multiplatform build script looks like this (Linux can be added as well):
```python
import platform
import os
import shutil

APP_NAME = 'Your App Name'

def remove(folder):
    if os.path.exists(folder):
        shutil.rmtree(folder)

def build_windows():
    return [
        'pyinstaller',
        'main.py',  # your main file with ui.run()
        '--name', APP_NAME,  # name of your app
        '--onedir',
        '--windowed',
        '--icon', 'AppIcon.ico'
    ]

def build_macos():
    return [
        'python',
        '-m', 'PyInstaller',
        'main.py',  # your main file with ui.run()
        '--name', APP_NAME,  # name of your app
        '--windowed',
        '--icon', 'AppIcon.icns'
    ]

build_matrix = {
    'Windows': build_windows,
    'Darwin': build_macos
}

if __name__ == "__main__":
    platform_name = platform.system()
    
    if platform_name not in build_matrix:
        print(f'Unsupported platform {platform_name}')
        sys.exit(1)

    subprocess.call(build_matrix[platform_name]())
```

**Comment by falkoschindler** [comment] 2024-03-28 07:19
Thanks @gotev!
This makes we wonder if we should provide such a versatile build script with the official NiceGUI package. This way we could bundle all gained knowledge from the [documentation](https://nicegui.io/documentation/section_configuration_deployment#package_for_installation) and [discussions](https://github.com/zauberzeug/nicegui/discussions?discussions_q=pyinstaller) and continuously improve the "recipe" until it works for everyone.

**Comment by falkoschindler** [comment] 2024-03-29 13:48
@gotev That would be awesome! I think we can start by putting it in the root directory of the repository. Once we have a release candidate, I'd love to make the executable available as an official script in the NiceGUI package. We probably just need to add something like this to pyproject.toml:
```toml
[tool.poetry.scripts]
your-command = "your_project_name.your_script:main"
```

**Comment by falkoschindler** [comment] 2024-10-17 07:03
Let's close this issue. It seems to have been caused by packaging from a virtual environment. I hope packaging works a little better with the new nicegui-pack script. Otherwise, feel free to re-open this or a new issue.

**Closed by falkoschindler** 2024-10-17 07:03 UTC
Labels: help wanted
