### ISSUE TITLE
NiceGUI Native Mode doesn't work

### ISSUE THREAD

**Issue by Heus-Sueh** [zauberzeug/nicegui#2406] opened 2024-01-21 01:18 UTC
### Description

If I try to run this code:

```py
from nicegui import app, ui

app.native.window_args['resizable'] = False
app.native.start_args['debug'] = True

ui.label('app running in native mode')
ui.button('enlarge', on_click=lambda: app.native.main_window.resize(1000, 700))

ui.run(
    title="Some app",
    reload=True,
    native=True, 
    window_size=(400, 300), 
    fullscreen=False)
```

it gives this error:
```
Exception has occurred: RuntimeError
A SemLock created in a fork context is being shared with a process in a spawn context. This is not supported. Please use the same context to create multiprocessing objects and Process.
```

**Comment by rodja** [comment] 2024-01-21 02:38
The code runs fine on my mac. What kind of environment are you using (OS, Python version, etc)?

**Comment by Heus-Sueh** [comment] 2024-01-21 11:28
> The code runs fine on my mac. What kind of environment are you using (OS, Python version, etc)?

Sorry, I forgot that detail, but here is my system:

> # System Details Report
> ## Report details
> - **Date generated:**                              2024-01-21 08:19:11
> 
> ## Hardware Information:
> - **Hardware Model:**                              Gigabyte Technology Co., Ltd. Z370M AORUS Gaming
> - **Memory:**                                      16.0 GiB
> - **Processor:**                                   Intel® Core™ i7-8700K × 12
> - **Graphics:**                                    NVIDIA GeForce GTX 1060 6GB
> - **Disk Capacity:**                               1.2 TB
> 
> ## Software Information:
> - **Firmware Version:**                            F14
> - **OS Name:**                                     Fedora Linux 39.20240120.0 (Silverblue)
> - **OS Build:**                                    (null)
> - **OS Type:**                                     64-bit
> - **GNOME Version:**                               45.3
> - **Windowing System:**                            Wayland
> - **Kernel Version:**                              Linux 6.6.11-200.fc39.x86_64
> - **Python Version:           Python 3.11.6**
> 
I'm running VS Code through the Arch Linux container, and this error seems similar or the same to the one described in this comment:
https://github.com/zauberzeug/nicegui/issues/1841#issuecomment-1793628283

**Comment by falkoschindler** [comment] 2024-01-21 15:17
Yes, it looks like a duplicate of #1841 to me.
Maybe we can analyze and discuss it over there and hopefully fix it once and for all. 🤞🏻

**Closed** 2024-01-21 15:17 UTC
