### ISSUE TITLE
Client has been deleted but is still being used. This is most likely a bug in your application code

### ISSUE THREAD

**Issue by Buruxianian** [zauberzeug/nicegui#3231] opened 2024-06-16 08:37 UTC
### Description

```
Client has been deleted but is still being used. This is most likely a bug in your application code. See https://github.com/zauberzeug/nicegui/issues/3028 for more information.
Stack (most recent call last):
  File "main.py", line 7, in <module>
  File "nicegui/ui_run.py", line 177, in run
    Server.instance.run()
  File "nicegui/server.py", line 36, in run
    super().run(sockets=sockets)
  File "uvicorn/server.py", line 65, in run
  File "asyncio/runners.py", line 44, in run
  File "nicegui/awaitable_response.py", line 29, in _fire
    self.fire_and_forget()
  File "nicegui/client.py", line 214, in send_and_forget
    self.outbox.enqueue_message('run_javascript', {'code': code}, target_id)
  File "nicegui/outbox.py", line 51, in enqueue_message
    self.client.check_existence()
  File "nicegui/client.py", line 331, in check_existence
    log.warning('Client has been deleted but is still being used. This is most likely a bug in your application code. '
```
I am using version 1.4.27, but I cannot locate the issue from the prompt and did not use ui. log(). Can you provide a solution to this problem.

**Comment by python-and-fiction** [comment] 2024-06-16 10:04
Any code of your problem?

**Comment by Buruxianian** [comment] 2024-06-16 10:41
@python-and-fiction 
I cannot minimize the code, it is a data monitoring application. At the beginning, it was running steadily, but after a period of time, I tried to access the application again but did not respond. The above are all the error prompts. I saw this error in the running log, but I am not sure which code went wrong.

**Comment by Buruxianian** [comment] 2024-06-16 10:42
@python-and-fiction
I cannot minimize the code, it is a data monitoring application. At the beginning, it was running steadily, but after a period of time, I tried to access the application again but did not respond. The above are all the error prompts. I saw this error in the running log, but I am not sure which code went wrong.

**Comment by python-and-fiction** [comment] 2024-06-16 10:59
> @python-and-fiction I cannot minimize the code, it is a data monitoring application. At the beginning, it was running steadily, but after a period of time, I tried to access the application again but did not respond. The above are all the error prompts. I saw this error in the running log, but I am not sure which code went wrong. Furthermore, it is strange that after waiting for a certain amount of time, the application can be successfully accessed.

Is there any issue caused by the combination of multi-threaded or multi process code with ui.log?
Is there a combination of dead loop code and client connection?

**Comment by falkoschindler** [comment] 2024-06-16 12:48
Thanks for reporting this problem, @Buruxianian!
However, I have to assume that this is a bug in your user code rather than NiceGUI. In #3206 there is a very similar discussion about this warning, where I posted some explanation of what is going on and a recommendation on how to proceed. Let's close this issue as a duplicate and continue the discussion over there. Maybe we can improve the warning and its traceback to avoid such confusion.

**Closed by falkoschindler** 2024-06-16 12:48 UTC
