### ISSUE TITLE
Files with whitespace in name don't get uploaded in native mode (MacOS 13.5.1, nicegui 1.3.11)

### ISSUE THREAD

**Issue by birchtree02** [zauberzeug/nicegui#1576] opened 2023-09-07 10:46 UTC
### Description

1. I'm trying to upload a file whose name includes spaces in native mode (MacOS 13.5.1, nicegui 1.3.11)
```python3
from nicegui import ui, events

def upload_zip(e: events.UploadEventArguments):
    ui.notify(f"Uploaded {e.name}")

ui.upload(on_upload=lambda e: upload_zip(e), auto_upload=True)
ui.run(native=True)
```

2. I expect the file to be uploaded
<img width="325" alt="Screenshot 2023-09-07 at 11 45 24" src="https://github.com/zauberzeug/nicegui/assets/18051539/ab47dcb0-0fa4-44c5-ac6f-27714158d398">

3. The upload gets stuck on 0
<img width="325" alt="Screenshot 2023-09-07 at 11 41 12" src="https://github.com/zauberzeug/nicegui/assets/18051539/3010af46-899a-4e4a-9c48-803a2d52d741">

This only happens in native mode, in the browser it works as expected.

**Comment by rodja** [comment] 2023-09-08 04:27
Yes, I can reproduce the error. Who can look into this?

**Comment by falkoschindler** [comment] 2023-09-15 11:18
Very strange, I _can't_ reproduce the bug.
I used the very same code example and the same filename.

**Comment by falkoschindler** [comment] 2023-10-05 13:39
Oh, I understand: The upload event is triggered, but the received file content is empty.

Modified test app to print the content:
```py
def upload_zip(e: events.UploadEventArguments):
    ui.notify(f'Uploaded "{e.content.read().decode()}"')

ui.upload(on_upload=upload_zip, auto_upload=True)
```

**Comment by falkoschindler** [comment] 2023-10-05 16:50
Ok, in a very interesting session with ChatGPT we boiled down the problem to a very simply reproduction:

```py
import webview

webview.create_window('Test', html='''
    <input type="file" onchange="displayFileSize()" />
    <script>
        function displayFileSize() {
            document.write(document.querySelector("input").files[0].size + " bytes");
        }
    </script>
''')
webview.start()
```

When picking a file like "test file.txt", the displayed size is 0.
When picking a file like "test_file.txt", the displayed size is not 0.
Tested with most recent pywebview 4.0.2.

I guess I'll file an issue over at https://github.com/r0x0r/pywebview/.

**Comment by falkoschindler** [comment] 2023-10-06 07:47
Yeah, the issue is already fixed on https://github.com/r0x0r/pywebview/. 👏 
So we only need to look out for the next pywebview update.

**Comment by falkoschindler** [comment] 2023-10-27 04:56
Yes, pywebview 4.4 just got released and it fixes our problem. 🎉

**Closed** 2023-10-27 04:55 UTC
Labels: bug, waiting
