### ISSUE TITLE
@ui.refreshable refreshes all browser instances

### ISSUE THREAD

**Issue by leusch** [zauberzeug/nicegui#1586] opened 2023-09-08 14:51 UTC
### Description

Scenario: I have the code below. The app is not running in native mode. The app is opened in multiple browsers.

Expected: When I click "Increment" in one browser, the number is incremented only in that browser.
Actual: The number is incremented in both browsers

```python
from nicegui import APIRouter, app, ui

@ui.refreshable
def my_number():
    ui.label(app.storage.user['num'])

def increment():
    app.storage.user['num'] = app.storage.user['num'] + 1
    my_number.refresh()

router = APIRouter(prefix='/my-page')

@router.page('/')
def page():
    app.storage.user['num'] = 1
    my_number()
    ui.button('Increment', on_click=increment)

app.include_router(router)

ui.run(storage_secret='foo')
```

**Comment by rodja** [comment] 2023-09-08 15:21
Thanks for reporting this! The api router is not relevant for this issue. It seems it can be fixed by moving the refreshable into the page-builder scope:

```py
@ui.page('/')
def page():

    @ui.refreshable
    def my_number():
        ui.label(app.storage.user['num'])

    def increment():
        app.storage.user['num'] = app.storage.user['num'] + 1
        my_number.refresh()

    app.storage.user['num'] = 1
    my_number()
    ui.button('Increment', on_click=increment)
```

But why does it not work otherwise?

**Comment by falkoschindler** [comment] 2023-09-15 11:50
I think this is expected behavior:

- If you define a single `ui.refreshable` globally and call it at multiple places (even on multiple clients or pages), it will automatically refresh all UI containers it created.
- If you, instead, create individual refreshables per client, each one is only responsible for refreshing the single container that was created by calling this individual instance. Therefore @rodja's example increments both clients independently.

Does that make sense? Or am I missing something?

**Comment by rodja** [comment] 2023-09-18 09:28
Thanks for the explanation @falkoschindler. You are right! The reported code in https://github.com/zauberzeug/nicegui/issues/1586#issue-1887837952 is similar to our chat example: Each user sees the same refreshable ui element. If that is not intended, the refreshable must be placed "on the page" and not globally.

**Closed by rodja** 2023-09-18 09:28 UTC
Labels: question
