### ISSUE TITLE
Issue with images

### ISSUE THREAD

**Issue by emil-n** [zauberzeug/nicegui#931] opened 2023-05-17 20:20 UTC
### Description

Images don't work in native=True mode, in the normal browser mode they work perfectly.

This is the error:
```*** First throw call stack:
(
        0   CoreFoundation                      0x000000018f34719c __exceptionPreprocess + 176
        1   libobjc.A.dylib                     0x000000018ee664d4 objc_exception_throw + 60
        2   _objc.cpython-310-darwin.so         0x000000012f52b040 PyObjCErr_ToObjCWithGILState + 1004
        3   _objc.cpython-310-darwin.so         0x000000012f50bd30 method_stub + 5644
        4   libffi.dylib                        0x000000019f0bff44 ffi_closure_SYSV_inner + 816
        5   libffi.dylib                        0x000000019f0b71e8 ffi_closure_SYSV + 56
        6   WebKit                              0x00000001b0268b38 _ZN6WebKit15NavigationState16NavigationClient33didReceiveAuthenticationChallengeERNS_12WebPageProxyERNS_28AuthenticationChallengeProxyE + 228
        7   WebKit                              0x00000001b04bac6c _ZN6WebKit19NetworkProcessProxy33didReceiveAuthenticationChallengeEN3PAL9SessionIDEN3WTF16ObjectIdentifierINS_26WebPageProxyIdentifierTypeEEERKNSt3__18optionalIN7WebCore18SecurityOriginDataEEEONS9_23AuthenticationChallengeEbNS4_INS_37AuthenticationChallengeIdentifierTypeEEE + 584
        8   WebKit                              0x00000001aff997f8 _ZN3IPC13handleMessageIN8Messages19NetworkProcessProxy33DidReceiveAuthenticationChallengeEN6WebKit19NetworkProcessProxyES5_FvN3PAL9SessionIDEN3WTF16ObjectIdentifierINS4_26WebPageProxyIdentifierTypeEEERKNSt3__18optionalIN7WebCore18SecurityOriginDataEEEONSE_23AuthenticationChallengeEbNS9_INS4_37AuthenticationChallengeIdentifierTypeEEEEEEvRNS_10ConnectionERNS_7DecoderEPT0_MT1_T2_ + 824
        9   WebKit                              0x00000001aff99058 _ZN6WebKit19NetworkProcessProxy36didReceiveNetworkProcessProxyMessageERN3IPC10ConnectionERNS1_7DecoderE + 436
        10  WebKit                              0x00000001b0805818 _ZN3IPC10Connection15dispatchMessageENSt3__110unique_ptrINS_7DecoderENS1_14default_deleteIS3_EEEE + 332
        11  WebKit                              0x00000001b08081ec _ZN3WTF6Detail15CallableWrapperIZN3IPC10Connection22enqueueIncomingMessageENSt3__110unique_ptrINS2_7DecoderENS4_14default_deleteIS6_EEEEE4$_15vJEE4callEv + 188
        12  JavaScriptCore                      0x00000001a967e454 _ZN3WTF7RunLoop11performWorkEv + 200
        13  JavaScriptCore                      0x00000001a967f320 _ZN3WTF7RunLoop11performWorkEPv + 36
        14  CoreFoundation                      0x000000018f2ce710 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 28
        15  CoreFoundation                      0x000000018f2ce6a4 __CFRunLoopDoSource0 + 176
        16  CoreFoundation                      0x000000018f2ce414 __CFRunLoopDoSources0 + 244
        17  CoreFoundation                      0x000000018f2cd01c __CFRunLoopRun + 828
        18  CoreFoundation                      0x000000018f2cc58c CFRunLoopRunSpecific + 612
        19  HIToolbox                           0x0000000198b01df4 RunCurrentEventLoopInMode + 292
        20  HIToolbox                           0x0000000198b01c30 ReceiveNextEventCommon + 648
        21  HIToolbox                           0x0000000198b01988 _BlockUntilNextEventMatchingListInModeWithFilter + 76
        22  AppKit                              0x00000001924ebf58 _DPSNextEvent + 636
        23  AppKit                              0x00000001924eb0f4 -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 716
        24  AppKit                              0x00000001924df558 -[NSApplication run] + 464
        25  libffi.dylib                        0x000000019f0b7050 ffi_call_SYSV + 80
        26  libffi.dylib                        0x000000019f0bfaf8 ffi_call_int + 1208
        27  _objc.cpython-310-darwin.so         0x000000012f5105fc PyObjCFFI_Caller + 1280
        28  _objc.cpython-310-darwin.so         0x000000012f5314f0 objcsel_vectorcall + 428
        29  Python                              0x0000000101958fd0 call_function + 132
        30  Python                              0x0000000101951370 _PyEval_EvalFrameDefault + 23864
        31  Python                              0x0000000101949db0 _PyEval_Vector + 360
        32  Python                              0x0000000101958fd0 call_function + 132
        33  Python                              0x000000010195037c _PyEval_EvalFrameDefault + 19780
        34  Python                              0x0000000101949db0 _PyEval_Vector + 360
        35  Python                              0x0000000101958fd0 call_function + 132
        36  Python                              0x000000010194fa6c _PyEval_EvalFrameDefault + 17460
        37  Python                              0x0000000101949db0 _PyEval_Vector + 360
        38  Python                              0x0000000101958fd0 call_function + 132
        39  Python                              0x0000000101951370 _PyEval_EvalFrameDefault + 23864
        40  Python                              0x0000000101949db0 _PyEval_Vector + 360
        41  Python                              0x0000000101823700 PyVectorcall_Call + 184
        42  Python                              0x000000010194bc5c _PyEval_EvalFrameDefault + 1572
        43  Python                              0x0000000101949db0 _PyEval_Vector + 360
        44  Python                              0x000000010194bc5c _PyEval_EvalFrameDefault + 1572
        45  Python                              0x0000000101949db0 _PyEval_Vector + 360
        46  Python                              0x0000000101958fd0 call_function + 132
        47  Python                              0x000000010195037c _PyEval_EvalFrameDefault + 19780
        48  Python                              0x0000000101949db0 _PyEval_Vector + 360
        49  Python                              0x0000000101958fd0 call_function + 132
        50  Python                              0x000000010195037c _PyEval_EvalFrameDefault + 19780
        51  Python                              0x0000000101949db0 _PyEval_Vector + 360
        52  Python                              0x0000000101958fd0 call_function + 132
        53  Python                              0x000000010194fa6c _PyEval_EvalFrameDefault + 17460
        54  Python                              0x0000000101949db0 _PyEval_Vector + 360
        55  Python                              0x0000000101958fd0 call_function + 132
        56  Python                              0x000000010194faf0 _PyEval_EvalFrameDefault + 17592
        57  Python                              0x0000000101949db0 _PyEval_Vector + 360
        58  Python                              0x00000001019b7e68 PyRun_StringFlags + 280
        59  Python                              0x00000001019b7c8c PyRun_SimpleStringFlags + 84
        60  Python                              0x00000001019deef0 pymain_run_command + 136
        61  Python                              0x00000001019de26c pymain_run_python + 240
        62  Python                              0x00000001019de13c Py_RunMain + 24
        63  Python                              0x00000001019df7c8 pymain_main + 56
        64  Python                              0x00000001019dfa8c Py_BytesMain + 40
        65  dyld                                0x000000018ee97f28 start + 2236
)
libc++abi: terminating due to uncaught exception of type NSException```

**Comment by 2000Nic** [comment] 2023-05-17 22:09
Sounds kinda similar to some issues we had at some point on my project. I wasn't the one fixing it in the end, but it seemed to be a Mac-specific problem, right? 

Would this be the right minimal reproduction or are there other native mode parameters specified? 

```python
from nicegui import ui

ui.image(image_url)
ui.run(native=True)
```

Small disclaimer: ours might have been a problem with opencv rather than nicegui, but I don't remember the details so I'll have to ask.

**Comment by rodja** [comment] 2023-05-18 03:15
On our macs (and linux systems) images work fine with native mode:

```py
from nicegui import ui

ui.image('https://nicegui.io/logo.png').classes('w-12 m-auto')
base64 = 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAUAAAAFCAYAAACNbyblAAAAHElEQVQI12P4//8/w38GIAXDIBKE0DHxgljNBAAO9TXL0Y4OHwAAAABJRU5ErkJggg=='
ui.image(base64).classes('w-2 h-2 m-auto')

ui.run(native=True)
```

Could you please provide a [minimal, executable code snippet reproducing the problem](https://en.wikipedia.org/wiki/Minimal_reproducible_example). This will allow us to identify and fix it more efficiently.

**Comment by emil-n** [comment] 2023-05-18 15:11
If someone is facing this problem, I managed to fix it by doing `pip install pyobjc-framework-Security`

**Comment by rodja** [comment] 2023-05-18 17:49
Why is that fixing anything? Can we close this issue?

**Comment by falkoschindler** [comment] 2023-05-25 11:57
I'll close the issue for now, since you seem to have fixed it. Feel free to re-open it when you have more information about it.

**Closed by falkoschindler** 2023-05-25 11:57 UTC
