### ISSUE TITLE
Async broken on v1.4.0 with FastAPI app

### ISSUE THREAD

**Issue by zilch42** [zauberzeug/nicegui#1874] opened 2023-10-25 02:26 UTC
### Description

The following async functions work on 1.3.18 but do nothing on 1.4.0 (no notification, no error, no indication something is happening) when using FastAPI. They work fine if using the normal `ui.run()`.

```python
from nicegui import ui, run
from fastapi import FastAPI
import asyncio
import requests 

async def async_task():
    ui.notify('Asynchronous task started')
    await asyncio.sleep(5)
    ui.notify('Asynchronous task finished')
    

async def handle_click():
    URL = 'https://httpbin.org/delay/1'
    response = await run.io_bound(requests.get, URL, timeout=3)
    ui.notify(f'Downloaded {len(response.content)} bytes')


@ui.page('/')
def home():
    ui.button('start async task', on_click=async_task)
    ui.button('Download', on_click=handle_click)

# works on 1.3.18, broken on 1.4.0
FastApp = FastAPI()
ui.run_with(FastApp)
if __name__ == '__main__':
    print('Please start with "uvicorn main:FastApp --reload --log-level debug --port 8000"')

# works on 1.3.18 and 1.4.0
# ui.run()
```

I guess it's related to #1849 but I didn't think there was a breaking change (I'm not using `@on_event("startup")` and `@on_event("shutdown")` explicitly).

**Comment by zilch42** [comment] 2023-10-25 02:36
Additional info, adding some logging I get the following error message on reloading the tab after clicking the buttons.

```
2023-10-25 13:05:35,035 [ERROR] [async_server] disconnect async handler error
Traceback (most recent call last):
  File "C:\Users\XXX\AppData\Local\miniconda3\envs\nice14\lib\site-packages\engineio\async_server.py", line 475, in run_async_handler
    return await self.handlers[event](*args)
  File "C:\Users\XXX\AppData\Local\miniconda3\envs\nice14\lib\site-packages\socketio\async_server.py", line 687, in _handle_eio_disconnect
    await self._handle_disconnect(eio_sid, n)
  File "C:\Users\XXX\AppData\Local\miniconda3\envs\nice14\lib\site-packages\socketio\async_server.py", line 575, in _handle_disconnect
    await self._trigger_event('disconnect', namespace, sid)
  File "C:\Users\XXX\AppData\Local\miniconda3\envs\nice14\lib\site-packages\socketio\async_server.py", line 635, in _trigger_event
    ret = handler(*args)
  File "C:\Users\XXX\AppData\Local\miniconda3\envs\nice14\lib\site-packages\nicegui\nicegui.py", line 151, in _on_disconnect
    client.handle_disconnect()
  File "C:\Users\XXX\AppData\Local\miniconda3\envs\nice14\lib\site-packages\nicegui\client.py", line 222, in handle_disconnect
    self._disconnect_task = background_tasks.create(handle_disconnect())
  File "C:\Users\XXX\AppData\Local\miniconda3\envs\nice14\lib\site-packages\nicegui\background_tasks.py", line 21, in create
    assert core.loop is not None
AssertionError
```

**Comment by falkoschindler** [comment] 2023-10-25 07:40
Thanks for the bug report, @zilch42! This a serious one. 🫤

But it seems to be a duplicate of https://github.com/zauberzeug/nicegui/issues/1870, and I think I found a fix and a workaround: https://github.com/zauberzeug/nicegui/issues/1870#issuecomment-1778683840.

**Closed by falkoschindler** 2023-10-25 07:40 UTC
Labels: bug

**Comment by zilch42** [comment] 2023-10-25 23:08
Thanks @falkoschindler I've tried adding the workaround from #1870 (full code below) but it doesn't seem to solve this issue. 

```python
from nicegui import ui, run, app
from nicegui.nicegui import _shutdown, _startup
from fastapi import FastAPI
import asyncio
import requests 

async def async_task():
    ui.notify('Asynchronous task started')
    await asyncio.sleep(5)
    ui.notify('Asynchronous task finished')
    

async def handle_click():
    URL = 'https://httpbin.org/delay/1'
    response = await run.io_bound(requests.get, URL, timeout=3)
    ui.notify(f'Downloaded {len(response.content)} bytes')


@ui.page('/')
def home():
    ui.button('start async task', on_click=async_task)
    ui.button('Download', on_click=handle_click)

# works on 1.3.18, broken on 1.4.0
FastApp = FastAPI()
ui.run_with(FastApp)
app.on_event('startup')(_startup)
app.on_event('shutdown')(_shutdown)

if __name__ == '__main__':
    print('Please start with "uvicorn main:FastApp --reload --log-level info --port 8000"')

# works on 1.3.18 and 1.4.0
# ui.run()
```

Still don't get any `ui.notify` popups and the same `assert core.loop is not None` error on page reload

**Comment by falkoschindler** [comment] 2023-10-26 04:57
@zilch42 In your case the app is called `FastApp`, so the workaround would be
```py
FastApp.on_event('startup')(_startup)
FastApp.on_event('shutdown')(_shutdown)
```

**Comment by zilch42** [comment] 2023-10-26 06:19
Oh that was silly of me. Thank you. I thought it was app from `nicegui.app`
