### ISSUE TITLE
Cant install package on Windows 8 64 bit (Rust compiler missing)

### ISSUE THREAD

**Issue by lopackhak333** [zauberzeug/nicegui#531] opened 2023-03-15 21:57 UTC
![Screenshot_3](https://user-images.githubusercontent.com/90701868/225452973-8771b8fa-0b03-4513-b0cd-29a970a6b60d.png)

**Comment by falkoschindler** [comment] 2023-03-15 22:01
This looks like a duplicate of https://github.com/zauberzeug/nicegui/issues/518.
@lopackhak333, can you confirm that you're on a 32 bit Windows machine?

**Comment by lopackhak333** [comment] 2023-03-15 22:03
> This looks like a duplicate of #518. @lopackhak333, can you confirm that you're on a 32 bit Windows machine?

I am on 64 bit system
Win 8.1....
I figured out that the problem is in the version of python probably

**Comment by rbeeli** [comment] 2023-03-16 01:44
Seems like you have a source package of `orjson` loaded instead of a wheel, that's why it tries to compile it, but fails, because the Rust compiler is missing. In your screenshot, you see a `orjson-3.8.7.tar.gz` package file instead of a wheel `*.whl`.

On my Ubuntu machine, I get a wheel: `orjson-3.8.7-cp310-cp310-manylinux_2_28_x86_64.whl`

Seems like for your system/architecture/OS/Python version combination there is no binary wheel available for `orjson`.
What's your Python version? It should be at least >=3.7.

**Comment by rodja** [comment] 2023-03-16 12:40
> I am on 64 bit system

In your screenshot I see "python37-32" in the site-packages path. This looks like an indication that you have a 32-bit Python installed. Can you try upgrading to newer version or switching to 64-bit?

**Comment by falkoschindler** [comment] 2023-03-27 09:55
I'll close this issue due to inactivity. But feel free to re-open it once you have new information for us, @lopackhak333!

**Closed** 2023-03-27 09:56 UTC
Labels: question

**Comment by tarensanders** [comment] 2023-05-02 23:34
Hi, just thought I'd leave a little note for anyone that ends up here from Google.

I was having the same issue as above (required Rust, not using a wheel), but I'm using 64bit Python on Mac (OSX 13.3.1). When trying to install `nicegui` with Python 3.10.11 `pip install nicegui` tries to install `orjson` version `3.8.11`. A quick look at the [available versions of orjson](https://pypi.org/simple/orjson/) shows no wheels that match this version of OSX (if you run `pip debug -v` it will show what versions pip thinks it can use).

The solution is just to pin `orjson` to `3.8.10` and install it before installing `nicegui`. Interestingly, this looks like it would only be a problem for Python>3.8 (and can confirm that I can just install nicegui on 3.8).

**Comment by rodja** [comment] 2023-05-03 03:29
@tarensanders do you have an idea why pip wants to install orjson `3.8.11`? NiceGUI only requires `3.8.6` or greater. Why is it not picking 3.8.10 automatically?

**Comment by tarensanders** [comment] 2023-05-03 04:03
@rodja the [pip dependency docs](https://pip.pypa.io/en/stable/topics/dependency-resolution/) say that it just picks the most recent version of the dependency which would be `3.8.11`. It says nothing about not choosing versions that need compiling, so I think it is behaving as expected. For whatever reason, `orjson` stopped building wheels that work with this version of OSX?

**Comment by skarussel** [comment] 2025-03-17 10:16
Following on this:

I see that orjson is now required in version = ">=3.9.15". For that dependency Cargo/Rust is strictly nescessary. Is there any workaround to install nicegui without Cargo/Rust?
