### ISSUE TITLE
ui.image() source does not auto-create route to local image when using binding

### ISSUE THREAD

**Issue by DaedlyKitten** [zauberzeug/nicegui#1853] opened 2023-10-22 02:05 UTC
### Description

```py
a = { 'a': '/home/kon/Pictures/DSC06478.JPG'}

ui.image().bind_source_from(a, 'a')
```

Will throw error:
```
http://127.0.0.1:8080/home/kon/Pictures/DSC06478.JPG not found
```

Same is true if source is set with `img1.source = some_local_path`.

**Comment by DaedlyKitten** [comment] 2023-10-22 02:38
I got it working with:

a={'a':'/home/kon/Pictures'}
app.add_media_files('/m1', a['a'])
aa=ui.image('/m1/DSC06478.JPG')
ui.run()

**Comment by rodja** [comment] 2023-10-22 04:07
Thanks for bringing this up @DaedlyKitten. I've already created a PR and hope to get it into the upcoming 1.4 release.

**Comment by falkoschindler** [comment] 2023-10-22 09:19
For reference: This is a duplicate of #1282.

**Comment by rodja** [comment] 2023-10-22 09:25
Oh, I was not aware of #1282. I'll close this one.

**Closed by rodja** 2023-10-22 09:25 UTC
Labels: enhancement
