### ISSUE TITLE
Infinite_scroll example broken on Safari

### ISSUE THREAD

**Issue by kleynjan** [zauberzeug/nicegui#2259] opened 2023-12-29 14:27 UTC
### Description

No biggie, but the current infinite_scroll example is actually a *finite* scroll on MacOS Safari. Something with the combination of offset, height and viewport height being used, leading to a stable end of document quite early on. I ran into this when using this example as starting point for another project.

As I am not handy with git etc, instead of a PR here is a modified version (works with Safari and Chrome):

```python
#!/usr/bin/env python3
import time

from nicegui import Client, ui

js = """
// scroll height as a percentage, returns null/None if no scrollbar 
(  (document.documentElement.scrollTop + document.body.scrollTop) / 
   (document.documentElement.scrollHeight - document.documentElement.clientHeight)) * 100 
"""


@ui.page("/")
async def page(client: Client):
    async def check():
        perc = await ui.run_javascript(js)
        if perc is None or perc > 70:
            ui.image(f"https://picsum.photos/640/360?{time.time()}")

    await client.connected()
    ui.timer(0.1, check)


ui.run()
```

**Comment by falkoschindler** [comment] 2023-12-30 08:56
Hi @kleynjan, strangely I can't reproduce this issue. I even upgraded to a more recent MacOS version to get the latest Safari 17.2.1. Which version do you use? Does the problem occur with a particularly large or small window?

Or can you explain, _why_ you're code should be better? Does any attribute like `pageYOffset`, `offsetHeight` or `innerHeight` have bad compatibility with certain browsers?

**Comment by kleynjan** [comment] 2023-12-30 12:12
Hi Falko, I am on Monterey 12.7.2 with Safari 17.2.1. See screenshot below that shows the "end state" (note the scoll bar) with the console logging the values for window.pageYOffset, document.body.offsetHeight and window.innerHeight. Problem occurs at every window size.

But you are right that the problem does not occur on Ventura! Feel free to close the issue. 

<img width="771" alt="screenshot" src="https://github.com/zauberzeug/nicegui/assets/1941801/627733e5-8bf2-4853-bf93-aa369ff0d951">

**Comment by kleynjan** [comment] 2023-12-30 12:17
Full disclosure, I just upgraded as well. When the issue surfaced yesterday I was on a previous Monterey version (12.7.1) and using Safari 16.X .

**Comment by kleynjan** [comment] 2024-01-05 08:41
Upgraded to Ventura 13.6.3 and Safari 16.6 and the issue is still there with the current infinite-scroll example. BUT: only on my two-monitor MacMini setup. (Same behaviour on both monitors, both using default resolution). My Macbook running the same versions is OK.

@falkoschindler, I leave it up to you if you want to close the issue. 

Cheers, Peter
 
<img width="576" alt="Screenshot 2024-01-05 at 09 26 38" src="https://github.com/zauberzeug/nicegui/assets/1941801/8a5736ad-b98e-4f6f-bfe2-b02595c6c6f0">

Console showing values for window.pageYOffset, document.body.offsetHeight and window.innerHeight at stable endpoint.

**Comment by falkoschindler** [comment] 2024-01-05 15:15
Thanks for the update, @kleynjan!
Unfortunately, I still can't reproduce the issue on my two-monitor setup. Let's close this issue. Even though it would be nice to fix this bug, it's just an example and not necessarily ready for production.

**Closed** 2024-01-05 15:15 UTC
Labels: question
