### ISSUE TITLE
Slider not updating floating label, slider position

### ISSUE THREAD

**Issue by vargasa** [zauberzeug/nicegui#838] opened 2023-04-25 20:34 UTC
### Description

Hello NiceGUI Devs! 

I'm using `ui.slider` (from `1.2.9`) with a handler that takes the event sender and updates its value based on some internal logic. The label that is bind to the value of the slider gets properly updated but neither the floating label, nor the position in the slider gets updated:

![Screenshot 2023-04-25 at 16-27-57 NiceGUI](https://user-images.githubusercontent.com/16821717/234396059-509e239a-9659-4c39-b903-c5e6abca363b.png)

Where I would expect the floating label on the top to be '50' instead of '47'. What would be the appropriate way to update the value/position/floating label of the slider?

### How to reproduce?

```python
import nicegui as ng
print(ng.__version__)

from nicegui import ui

def on_value_change(sender, event):
    print(event)
    closest_tenth = round(sender.value / 10) * 10
    print(f'closest_tenth: {closest_tenth}')
    sender.value = closest_tenth
    sender.update()

slider = ui.slider(
    min=0, 
    max=100, 
    value=50, 
    step=1
).props('label-always').classes('w-100 q-mt-lg')

slider.on(
    type = 'change',
    handler = lambda event: on_value_change(slider, event)
)

ui.label().bind_text_from(slider, 'value')
ui.run()
```

**Comment by rodja** [comment] 2023-04-26 03:29
Thanks for spotting this bug, @vargasa! Is that caused by some logic in our outbox, @falkoschindler? Here is a slightly shorter reproduction:

```py
async def on_value_change(args: events.ValueChangeEventArguments):
    closest_tenth = round(args.sender.value / 10) * 10
    ui.notify(f'changing from {args.sender.value} to {closest_tenth}')
    args.sender.set_value(closest_tenth)


slider = ui.slider(min=0, max=100, value=50, on_change=on_value_change) \
    .props('label-always').classes('w-100 q-mt-lg')
ui.label().classes('text-4xl').bind_text_from(slider, 'value')
```

I noticed that clicking once somewhere on the slider yields the expected behaviour of snapping to the closest tenth. But with dragging the value is computed and updated without affecting the slider in the browser.

**Comment by falkoschindler** [comment] 2023-04-26 11:51
That's very strange. All possible explanations I had in mind proved to be wrong.
But it looks like I found a reproduction without NiceGUI:

```html
<!DOCTYPE html>
<html>
  <head>
    <link href="https://cdn.jsdelivr.net/npm/quasar@2.11.10/dist/quasar.prod.css" rel="stylesheet" type="text/css" />
  </head>
  <body>
    <div id="q-app">
      <p>Test</p>
      <q-slider :model-value="sliderValue" :min="0" :max="100" @update:model-value="snap" label-always />
    </div>
    <script src="https://cdn.jsdelivr.net/npm/vue@3/dist/vue.global.prod.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/quasar@2.11.10/dist/quasar.umd.prod.js"></script>
    <script module>
      const app = Vue.createApp({
        setup() {
          return {
            sliderValue: Vue.ref(50),
          };
        },
        methods: {
          snap(value) {
            this.sliderValue = Math.round(value / 10) * 10;
            console.log(value, this.sliderValue);
          },
        },
      });
      app.use(Quasar);
      app.mount("#q-app");
    </script>
  </body>
</html>
```

Has anyone an idea what is going on?

---

@vargasa Apart from that, just for the record: Snapping to a certain step size can be done with the `step` parameter. But your actual `on_value_change` handler is probably more complex.

**Comment by falkoschindler** [comment] 2023-04-26 12:03
I posted a question on StackOverflow:
https://stackoverflow.com/questions/76110518/how-to-modify-quasars-slider-value-on-change

**Comment by vargasa** [comment] 2023-04-26 20:50
Hi @falkoschindler @rodja. Thank you for your quick response! @falkoschindler, that's right 😃, the current `on_value_change` depends on a non-linearly increasing float filtered from user input so I simplified the implementation so to be able to reproduce the behavior. I see the same unexpected behavior when using a [`q-range` with `model-value`](https://v1.quasar.dev/vue-components/range#usage)

**Comment by pramineni-01** [comment] 2023-04-28 16:03
> ```python
> closest_tenth
> ```

@vargasa if i set the step to 10, am not seeing the issue with floating label and the slider position. Could you try it once?
My observation is the value is correctly set in the control by the handler. But the value is not always used in setting the slider position or the floating label.

**Comment by falkoschindler** [comment] 2023-07-26 14:32
Unfortunately this bug still occurs with the most recent Quasar v2.12.3. Since we can't do much about it on our side, I'll close this issue. But maybe someone can file a bug over at https://github.com/quasarframework/quasar/?

**Closed** 2023-07-26 14:32 UTC
Labels: bug
