### ISSUE TITLE
Provide example to use hamburger menu button for drawer expanding/collapsing

### ISSUE THREAD

**Issue by wwoods** [zauberzeug/nicegui#308] opened 2023-01-28 03:13 UTC
Quasar seems to allow a hamburger menu button that expands or collapses a drawer: https://github.com/quasarframework/quasar/blob/dev/docs/public/examples/QDrawer/Menu.vue

It would be nice to see how to do this within NiceGUI, since it's a standard layout choice for more real estate.

**Comment by falkoschindler** [comment] 2023-02-10 13:21
In [517ec0f](https://github.com/zauberzeug/nicegui/commit/517ec0fa8a1478533e36eea9096ff63fef764f0b) I improved the page layout elements:

- added docstrings,
- derived header, footer and drawers from `ValueElement` so that you can toggle their `value` property,
- added new initializer parameters, and
- improved the type annotation using literal strings here and there.

Here is an example for hamburger menu buttons toggling all four panels:

```py
ui.label('This is the page content')

with ui.header().classes('items-center') as header:
    ui.button(on_click=lambda: left_drawer.set_value(not left_drawer.value)).props('flat color=white icon=menu')
    ui.label('This is a header').classes('mx-auto')
    ui.button(on_click=lambda: right_drawer.set_value(not right_drawer.value)).props('flat color=white icon=menu')

with ui.left_drawer().classes('bg-blue-100') as left_drawer:
    ui.label('This is a left drawer')

with ui.right_drawer().classes('bg-blue-100') as right_drawer:
    ui.label('This is a right drawer')

with ui.footer() as footer:
    ui.label('This is a footer')

with ui.page_sticky(position='top-right', x_offset=20, y_offset=20):
    ui.button(on_click=lambda: header.set_value(not header.value)).props('fab icon=menu')

with ui.page_sticky(position='bottom-right', x_offset=20, y_offset=20):
    ui.button(on_click=lambda: footer.set_value(not footer.value)).props('fab icon=menu')
```

**Comment by falkoschindler** [comment] 2023-02-10 13:40
I also updated the example in the API reference.

@rodja I think we can close this issue. Do you agree?

**Comment by rodja** [comment] 2023-02-10 14:03
Yes! I just pushed a new example combining a foldable menu with tabs: https://github.com/zauberzeug/nicegui/commit/5e1610bad6216e20a148fd6f221e41921523b268.

**Closed by rodja** 2023-02-10 14:03 UTC
Labels: documentation, enhancement

**Comment by falkoschindler** [comment] 2023-02-10 15:17
Small caveat:
Setting the initial `value` for a drawer to `False` doesn't seem to work.
But it works for headers and footer.

**Comment by rodja** [comment] 2023-02-10 15:36
> Setting the initial value for a drawer to False doesn't seem to work.

That is maybe caused by internal media-queries? The drawer automatically hides for small window sizes...

**Comment by falkoschindler** [comment] 2023-02-10 15:53
[d0a27da](https://github.com/zauberzeug/nicegui/commit/d0a27da30163494ff2e93e8d0a8264a110070375): I found an obsolete prop that is not needed anymore since we explicitly set the value.
