### ISSUE TITLE
Firefox reloads the page if the application link is opened

### ISSUE THREAD

**Issue by longnetwork** [zauberzeug/nicegui#1687] opened 2023-09-25 16:50 UTC
### Description

Test Code:
```py
from nicegui import ui

@ui.page('/')
def index_page():
    btn = ui.button('open application')
    btn.on('click', lambda: ui.open('tg://resolve?domain=telegram'))
   
ui.run(reload=False)
```

This breaks the rendering logic. Everything is fine in other browsers.

The error occurs at line 244 in the front-end script:
```py
              window.socket.emit("handshake", (ok) => {
                if (!ok) {
                  console.log('reloading because handshake failed');  // HERE !!!
                  window.location.reload();
                }
                document.getElementById('popup').style.opacity = 0;
              });
```

**Comment by longnetwork** [comment] 2023-09-25 17:02
The error disappears with the `new_tab=True` flag
But then there remains a green open tab

**Comment by falkoschindler** [comment] 2023-09-27 07:34
Thanks for reporting this issue, @longnetwork!

I think line 244 isn't the root cause. Firefox seems to reload the page when running something like
```js
window.open('mailto:info@me.com', '_self')
```
and then the handshake fails.

I wonder what we can do about it. Maybe we can't prevent Firefox from reloading and need to focus on fixing the handshake. But I'm not sure yet.

**Comment by falkoschindler** [comment] 2023-09-27 07:41
Oh, I just noticed that I don't get any handshake problems. The page reloads cleanly. So except from an unfortunate page reload in Firefox, which we might not be able to do anything about, I don't see any problem.

@longnetwork Do you get any JavaScript errors or rendering problems, or is it just the reload that bugs you?

**Comment by longnetwork** [comment] 2023-10-03 12:39
For me the bug is just a reboot. This may be a temporary handshake bug in the current version of Firefox for Linux (Mozilla Firefox 117.0.1). I solved it by saving the page state together with the `@ui.refreshable` decorator, so that there would be no dependence on page reloading. Page rendering in Firefox is correct

**Comment by falkoschindler** [comment] 2023-10-03 15:33
Ok, given the constraints and it being potentially out of our control, I'll close this issue for now.
If there are future updates or if anyone has more insights on this, please feel free to reopen or comment.

**Closed by falkoschindler** 2023-10-03 15:33 UTC
Labels: bug
