### ISSUE TITLE
some times the reload dont work

### ISSUE THREAD

**Issue by v479038280** [zauberzeug/nicegui#1245] opened 2023-07-24 10:46 UTC
### Description

There is nothing wrong ,but the reload doesnot happen automatically  ,I have to rerun the '' python main.py" manually ,dont know why

**Comment by falkoschindler** [comment] 2023-07-24 12:28
Does it happen with all NiceGUI apps, or just a specific one? Can you show a minimum reproducible example?

**Comment by v479038280** [comment] 2023-07-24 22:56
> Does it happen with all NiceGUI apps, or just a specific one? Can you show a minimum reproducible example?
I found that when I run the main.py using `python main.py` ,the reload works fine. It happens when I run the script in VScode using the button **run the python file**

**Comment by falkoschindler** [comment] 2023-07-25 06:55
Ok, I see.
Can you, please, put the following minimal uvicorn example into a file called "test.py" and try running it via VSCode? Does the auto-reload work?

```py
#!/usr/bin/env python3
import uvicorn
from fastapi import FastAPI

app = FastAPI()

@app.get('/')
def read_root():
    return {'Hello': 'World'}

if __name__ == '__main__':
    uvicorn.run('test:app', host='0.0.0.0', port=8000, reload=True)
```

**Comment by falkoschindler** [comment] 2023-07-25 18:08
> then I try the code that didn't work before ,it also works too, I haven't added these code above yet, a little strange.
So is the problem solved?
Since the problem description is still very vague, unreproducible and you didn't answer my questions, I tend to close this issue.

**Comment by v479038280** [comment] 2023-07-25 18:13
> > then I try the code that didn't work before ,it also works too, I haven't added these code above yet, a little strange.
> 
> So is the problem solved? Since the problem description is still very vague, unreproducible and you didn't answer my questions, I tend to close this issue.

Actually is The problem dosnot apper again ,I do nothing

**Closed** 2023-07-25 18:14 UTC
