### ISSUE TITLE
socket.io connection pending on brave browser?

### ISSUE THREAD

**Issue by Smug246** [zauberzeug/nicegui#2653] opened 2024-03-02 21:05 UTC
### Description

No idea why this is happening but on the brave browser my app loads by i cant interact properly with any of the elements. so i looked in the network developer tools and it says the socket.io is pending whereas if i open it on google chrome it works fine.

Brave Browser:
![image](https://github.com/zauberzeug/nicegui/assets/99215486/77e3947d-9ea0-4e53-84fa-13b158bf848f)

Google Chrome:
![image](https://github.com/zauberzeug/nicegui/assets/99215486/1f6ed846-88fa-4e46-acfb-ee53c957850a)

**Comment by rodja** [comment] 2024-03-03 01:47
Strange. Brave works fine in my tests. Have you tested a minimal "hello word" example? Can anybody else reproduce this?

**Comment by Smug246** [comment] 2024-03-03 11:29
its only when there's an element that has some sort of dropdown/clicking element. i'll screen record when i'm home

**Comment by falkoschindler** [comment] 2024-04-01 09:21
@Smug246 Do you have any news for us about this issue? Does the problem still persist?

**Comment by Smug246** [comment] 2024-04-01 15:10
no i'm too sure about this one. definitely something to do with the brave browser. so i mainly just use google chrome when testing.

**Comment by falkoschindler** [comment] 2024-04-03 13:15
Ok, since we don't have a reproduction, I'll close this issue. Feel free to re-open it in case you have new information.

**Closed by falkoschindler** 2024-04-03 13:15 UTC
Labels: question
