### ISSUE TITLE
`ui.number`: change event argument differs from `value` property

### ISSUE THREAD

**Issue by falkoschindler** [zauberzeug/nicegui#3142] opened 2024-05-29 21:18 UTC
### Discussed in https://github.com/zauberzeug/nicegui/discussions/3110

<div type='discussions-op-text'>

<sup>Originally posted by **CrystalWindSnake** May 21, 2024</sup>
### Question

```python
# notify 0 when deleting value
ui.number(value=66, on_change=lambda e: ui.notify(f"{e.value=} {e.sender.value=}"))
```
When the input is cleared, e.value is `0` , expect it to be `None` . this is bug?

</div>

**Comment by Lucas-lyh** [comment] 2024-06-04 02:19
It seems like this is designed to be 0.
In elements/number.py, overwrited function `_value_to_event_value` function convert value to zero when value is None.
Should it keep None?
```python
    def _value_to_event_value(self, value: Any) -> Any:
        return float(value) if value else 0
```

**Comment by frankvp11** [comment] 2024-06-19 18:32
Hmm, this is interesting.
I was playing around with this and noticed some interesting things.
Firstly, as is mentioned above, the fix for this issue would be what @Lucas-lyh  described. Switch the 0 to a None and it works. I'll submit a PR for this once I get home (unless either of you want to do it @falkoschindler )
However, the reason I said this was interesting, is because I tried putting in letters into the number element. I realize that the reason you can input 'e' is because of numbers like 1e6, as this is a common representation of them. However, the reason I am intrigued is because you can put the 'e' there without a prefix. Is this the expected behaviour? Are we supposed to be able to put e7, or should we require it to have a prefix?

**Closed** 2024-06-26 14:03 UTC
Labels: bug
