### ISSUE TITLE
Can't run Nicegui from __main__

### ISSUE THREAD

**Issue by ghbm-itk** [zauberzeug/nicegui#4106] opened 2024-12-16 09:56 UTC
### Description

I'm trying to create an app which I want to run using `python -m MyApp`.
For this I have created a `__main__.py` which contains `ui.run()`.

I get the following error:

```
ERROR:    Traceback (most recent call last):
  File "C:\Repos\GHBM\OpenPostbud\.venv\Lib\site-packages\starlette\routing.py", line 693, in lifespan
    async with self.lifespan_context(app) as maybe_state:
  File "C:\Users\az68933\AppData\Local\Programs\Python\Python312\Lib\contextlib.py", line 210, in __aenter__
    return await anext(self.gen)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Repos\GHBM\OpenPostbud\.venv\Lib\site-packages\nicegui\nicegui.py", line 29, in _lifespan
    await _startup()
  File "C:\Repos\GHBM\OpenPostbud\.venv\Lib\site-packages\nicegui\nicegui.py", line 113, in _startup
    raise RuntimeError('\n\n'
RuntimeError:

You must call ui.run() to start the server.
If ui.run() is behind a main guard
   if __name__ == "__main__":
remove the guard or replace it with
   if __name__ in {"__main__", "__mp_main__"}:
to allow for multiprocessing.

ERROR:    Application startup failed. Exiting.
```

I have used `__main__.py` in another project which uses Nicegui 1.4.12 and that works.

I'm unsure how to create a minimum example without attaching a complete project.

**Comment by falkoschindler** [comment] 2024-12-16 14:53
Hi @ghbm-itk,

This is a known problem which has been discussed in #1993. We're still looking for a solution that plays nicely with the optional auto-reload.

I wonder how this worked with version 1.4.12 tough. If this is indeed the case, we could bisect the Git history to find where it breaks.

Anyway, I'll close this issue as duplicate of #1993. Let's continue the discussion over there.

**Closed by falkoschindler** 2024-12-16 14:53 UTC

**Comment by ghbm-itk** [comment] 2024-12-17 08:20
Okay, I didn't know reload was the culprit. I have set that to False in my other app, so that explains why it works there
