### ISSUE TITLE
Mermaid & Dark Mode

### ISSUE THREAD

**Issue by quenio** [zauberzeug/nicegui#1637] opened 2023-09-16 23:56 UTC
### Description

My app is initialized in dark mode. Works great most of the time, but it flickers on pages that have a mermaid element.

**Comment by falkoschindler** [comment] 2023-09-17 13:26
Can you confirm that it happens with this minimum example?
```py
from nicegui import ui

ui.mermaid('''
graph LR;
    A --> B;
    A --> C;
''')

ui.run(dark=True)
```

Which OS and browser are you using? Are there any JavaScript messages on the developer console?

**Comment by quenio** [comment] 2023-09-19 02:53
It does happen with the minimal example (listed above) as well.

OS: macOS Ventura 13.4.1
Browser: Safari 16.5.1

NOTE: The issue does _not_ happen on the same OS with Chrome.

Here's the console output on both web browsers:
```
[Warning] cdn.tailwindcss.com should not be used in production. To use Tailwind CSS in production, install it as a PostCSS plugin or use the Tailwind CLI: https://tailwindcss.com/docs/installation (tailwindcss.min.js, line 62)
[Warning]  (tailwindcss.min.js, line 1)
[Warning] warn – "-" – "No utility classes were detected in your source files. If this is unexpected, double-check the `content` option in your Tailwind CS…" (tailwindcss.min.js, line 1)
"No utility classes were detected in your source files. If this is unexpected, double-check the `content` option in your Tailwind CSS configuration."
[Warning] warn – "-" – "https://tailwindcss.com/docs/content-configuration" (tailwindcss.min.js, line 1)
```

**Comment by falkoschindler** [comment] 2023-09-19 05:28
Strange. I'm on MacOS 13.4.1 and I don't see any flickering on Safari 16.5.2.
The console output doesn't look suspicious.
Can anybody help?

**Comment by quenio** [comment] 2023-09-22 17:28
Is there a way I could force the page to start with a dark background color before Quasar or Tailwind is loaded? That might work around the issue.

**Comment by quenio** [comment] 2023-09-22 17:30
New info: the problem does not seem to be related to mermaid. I am seeing it now in other pages. Not able to identify which element is causing it.

**Comment by rodja** [comment] 2023-09-23 02:42
> Is there a way I could force the page to start with a dark background color before Quasar or Tailwind is loaded? That might work around the issue.

You can use `.style` property on elements (or query objects). Another alternative may be to use `ui.add_head_html` to inject a block of `<style ...` definitions.

**Comment by falkoschindler** [comment] 2023-09-29 10:11
@quenio Could you narrow it down to what is causing the flickering?
Since it happens with the minimal example https://github.com/zauberzeug/nicegui/issues/1637#issuecomment-1722477274 but also on pages without Mermaid, and we can't reproduce it on our system (Mac OS Ventura 13.4.1, Safari 16.5.2), I'm a bit out of ideas.

**Comment by falkoschindler** [comment] 2023-10-06 17:41
It's still unclear _when_ the flickering actually occurs. So there's not much we can do.
Therefore, I'll close this issue for now. Feel free to re-open it once you have more information or even a reproduction.

**Closed by falkoschindler** 2023-10-06 17:41 UTC
Labels: help wanted, question
