### ISSUE TITLE
Not able to import texture data to OBJ/ STL files

### ISSUE THREAD

**Issue by kowshik1234** [zauberzeug/nicegui#1895] opened 2023-10-26 15:40 UTC
### Description

When trying to import the OBJ files only the vertices and the outer body is rendered however I need the color data be also loaded. How to do this? Does nicegui supports any of these functionalities?

**Comment by falkoschindler** [comment] 2023-10-26 15:43
Duplicate of https://github.com/zauberzeug/nicegui/discussions/1892.

**Closed** 2023-10-27 04:57 UTC
