### ISSUE TITLE
Erroneous occulusion rendering in 3D scenes

### ISSUE THREAD

**Issue by maria-korosteleva** [zauberzeug/nicegui#3673] opened 2024-09-04 13:07 UTC
I'm trying to display a 3D scene consisting of a body model and a garment. There is a relatively small gap between the two, which seems to be confusing occulision estimation and creating weird images as below: 
![image](https://github.com/user-attachments/assets/0eff9e2d-76b0-422c-8f2f-73c6c3195dc3)

The same two 3D objects are rendered fine using an external renderer: 
![Configured_design_3D_render_front](https://github.com/user-attachments/assets/97bf8c2a-6aad-4fbb-9583-9293b4c794af)

My best guess is there should be a setting that influences z-buffer resolution, which influences the differentiation of the objects that are close to each other in the depth direction from the camera. However, I do not seem to find it in niceGUI. Is it available? 

Here is the loading code snippet, for reference: 
```py
with ui.scene(
	width=1024,
	height=800, 
	camera=camera, 
	grid=False, 
	background_color=bg_color   
	) as ui_3d_scene:
	ui_3d_scene.stl(
			'/body/mean_all.stl' 
		).rotate(np.pi / 2, 0., 0.).material(color='#000000')

	ui_3d_scene.gltf(
		f'geo/{self.garm_3d_filename}', 
	).scale(0.01).rotate(np.pi / 2, 0., 0.).material(side='double')
```

The same two objects render in https://threejs.org/editor/ without a problem: 

![image](https://github.com/user-attachments/assets/749af9d8-ed80-4ed7-989d-bb4832ccd1b3)

The question was not answered so assume there is an issue to tackle here =)

_Originally posted by @maria-korosteleva in https://github.com/zauberzeug/nicegui/discussions/3514_

**Comment by Nikhiludupa** [comment] 2024-09-04 13:07
try this
https://gofile.io/d/yMHabA
select the desired compiler in the installer

**Comment by falkoschindler** [comment] 2024-09-06 14:59
Ok, I agree this might be an issue with NiceGUI. But since we already experimented and collected some insights over at #3514, I suggest we leave this ticket open but continue the discussion over there to avoid duplication. 🙂

**Comment by falkoschindler** [comment] 2024-09-08 17:08
As explained in https://github.com/zauberzeug/nicegui/discussions/3514#discussioncomment-10570807, I don't think this is a problem with NiceGUI, but caused by the specific camera parameters. Therefore I'll close this issue.

**Closed by falkoschindler** 2024-09-08 17:08 UTC
Labels: help wanted
