### ISSUE TITLE
ui.expansion() elements don't seem to work in native mode

### ISSUE THREAD

**Issue by 2000Nic** [zauberzeug/nicegui#873] opened 2023-05-02 06:56 UTC
### Description

Settings for native mode:
```python
reload=False
windowsize=(1920,1080)
title="test"
```

As the title says the ui.expansion elements don't seem to work when using native mode. Everything else in the program works.

**Comment by falkoschindler** [comment] 2023-05-02 07:40
I'm trying to find a minimal reproduction. But this works for me:
```py
from nicegui import ui

with ui.expansion('Expansion'):
    ui.label('inside')

ui.run(native=True, reload=False)
```

**Comment by 2000Nic** [comment] 2023-05-02 07:45
I've been trying that for a bit as well. I'll report back if I find the actual problem. It only fails fails in native mode in our main program though, so there must be something else that changes too.

**Comment by falkoschindler** [comment] 2023-05-07 16:14
Ok. I'll close this issue for now, because `ui.expansion` _does_ work in native mode.
@2000Nic Feel free to re-open it or open a new issue if you find more information about the actual problem.

**Closed by falkoschindler** 2023-05-07 16:14 UTC
Labels: question
