### ISSUE TITLE
Mousewheel changes number element values  with null "wheel" event handler

### ISSUE THREAD

**Issue by parlance-zz** [zauberzeug/nicegui#3878] opened 2024-10-15 20:49 UTC
### Description

I thought it might be nice to have the mouse wheel roll through values on my number elements so I added an event handler for wheel events on those controls and found some weird behavior.

After some messing around it turns out that although mouse wheel interaction with number elements isn't enabled by default, adding an event handler for the wheel event on the number element actually enables my desired functionality, _even if the event handler does nothing_. If I try to use the deltaY argument to change the element value it just causes weirdness because the value is already being updated.

Code to reproduce (on 2.2.0):
```py
from nicegui import ui

my_number_element = ui.number(label="My Number", value=10, step=1)
my_number_element.on("wheel", lambda: None) #comment this line and the mouse wheel no longer does anything when the element is focused

ui.run()
```

I think the way it behaves is great when enabled, but I'm wondering if this behavior was intended to be always on. It seems weird to enable the behavior with a null event handler.

**Comment by falkoschindler** [comment] 2024-10-18 18:14
Hi @parlance-zz,

Looks like you discovered an interesting "feature" in Quasar's QInput. It doesn't seem to be documented, but I managed to reproduce it with the following minimal Quasar example:
```html
<html>
  <head>
    <link href="https://fonts.googleapis.com/css?family=Roboto:400|Material+Icons" rel="stylesheet" type="text/css" />
    <link href="https://cdn.jsdelivr.net/npm/quasar@2.17.0/dist/quasar.prod.css" rel="stylesheet" type="text/css" />
  </head>
  <body>
    <div id="q-app">
      <q-input v-model.number="myNumber" type="number" @wheel="noop"></q-input>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/vue@3/dist/vue.global.prod.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/quasar@2.17.0/dist/quasar.umd.prod.js"></script>
    <script>
      const app = Vue.createApp({
        setup() {
          const myNumber = Vue.ref(10);
          return {
            myNumber,
            noop: () => {},
          };
        },
      });
      app.use(Quasar);
      app.mount("#q-app");
    </script>
  </body>
</html>
```

Maybe you'd like to discuss it over at https://github.com/quasarframework/quasar. But I'd rather not change `ui.number` to either rely on this behavior or explicitly suppress it. Who knows how QInput behaves in the next version of Quasar. Therefore I'll close this issue as "won't fix".

**Closed by falkoschindler** 2024-10-18 18:14 UTC
